import { useRef } from 'react';
import { Candy, Citrus, Droplet, Flame, Leaf, Sparkles, Zap } from 'lucide-react';
import CrossSectionShell, { type CrossSectionFact } from '../food3d/CrossSectionShell';
import FlatCutStage from '../../components/FlatCutStage';
import { MICRO } from './microStructures';
import { FOOD_MODELS, NO_CUT_FOODS, foodSizeOf } from '../food3d/foodRegistry';
import FitScale from '../food3d/FitScale';

/**
 * The microscope screen for foods with no 3D model.
 *
 * Everything below the lens is the same as the modelled foods — same chips, same
 * tissue drawing, same one-fact-at-a-time card — so a child cannot tell that a
 * burger took a different route through the app than an apple did. Only the left
 * panel differs: a cut icon instead of a cut mesh.
 *
 * A food listed here should have no entry in `FOOD_CROSS_SECTIONS` — the 3D screen
 * is the one that gets shown, and two copies of the same facts would let them
 * drift apart. Every number below comes straight off the client's sheet.
 */
const FLAT_FACTS: Record<string, CrossSectionFact[]> = {
  corn: [
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Natural Sugar',
      tag: '≈6–7 g',
      color: '#ff6b9d',
      fact: 'Sweetcorn really is sweet, but only ≈6–7 g per 100 g — and ≈2.7 g of fibre comes with it.',
    },
    {
      id: 'protein',
      icon: <Zap size={20} color="#4dd6ff" />,
      name: 'Protein',
      tag: '≈3.4 g',
      color: '#4dd6ff',
      fact: 'More protein than most vegetables give you: ≈3.4 g in every 100 g, for growing.',
    },
    {
      id: 'minerals',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Potassium',
      tag: '≈218 mg',
      color: '#06d6a0',
      fact: '≈218 mg of potassium and ≈6 mg of Vitamin C in a 100 g helping.',
    },
  ],
  broccoli: [
    {
      id: 'vitamin-c',
      icon: <Citrus size={20} color="#8bd450" />,
      name: 'Vitamin C',
      tag: '≈80 mg',
      color: '#06d6a0',
      fact: '≈80 mg of Vitamin C in a 90 g serving, plus ≈55 µg of folate and ≈40 mg of calcium.',
    },
    {
      id: 'fibre',
      icon: <Leaf size={20} color="#2c7a3a" />,
      name: 'Fibre',
      tag: '≈2.3 g',
      color: '#8bd450',
      fact: '≈2.3 g of fibre and only ≈1.5 g of sugar — and ≈81 g of the serving is water.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Barely Any Calories',
      tag: '≈30 kcal',
      color: '#ff8c42',
      fact: 'A whole serving is about 30 kcal and still hands you ≈2.5 g of protein.',
    },
  ],
  peanuts: [
    {
      id: 'fat',
      icon: <Droplet size={20} color="#4dd6ff" />,
      name: 'The Fat',
      tag: '≈14 g',
      color: '#4dd6ff',
      fact: 'Almost half a handful is fat — ≈14 g — and that is why 30 g carries ≈170 kcal.',
    },
    {
      id: 'protein',
      icon: <Zap size={20} color="#1c6b48" />,
      name: 'Protein',
      tag: '≈7.5 g',
      color: '#06d6a0',
      fact: '≈7.5 g of protein from one small handful, with only ≈1 g of sugar.',
    },
    {
      id: 'minerals',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Iron & Folate',
      tag: '≈1.3 mg iron',
      color: '#e76f51',
      fact: '≈1.3 mg of iron, ≈70 µg of folate and ≈200 mg of potassium in 30 g.',
    },
  ],
  'soft-drink': [
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Added Sugar',
      tag: '≈35 g',
      color: '#ff6b9d',
      fact: '≈35 g of sugar dissolved in one can. Nothing to chew, and nothing to slow it down.',
    },
    {
      id: 'empty',
      icon: <Zap size={20} color="#9aa5ad" />,
      name: 'Nothing Else',
      tag: '0 g protein',
      color: '#9aa5ad',
      fact: 'No protein, no fat and no fibre at all — just carbonated water, sugar, fizz and food acids.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Liquid Energy',
      tag: '≈140 kcal',
      color: '#ff8c42',
      fact: 'Every one of those ≈140 kcal comes from sugar, so you get the rush without any food.',
    },
  ],
  'potato-chips': [
    {
      id: 'fat',
      icon: <Droplet size={20} color="#4dd6ff" />,
      name: 'The Fat',
      tag: '≈16–18 g',
      color: '#4dd6ff',
      fact: 'One small 50 g packet soaks up ≈16–18 g of oil while it fries.',
    },
    {
      id: 'salt',
      icon: <Sparkles size={20} color="#e76f51" />,
      name: 'The Salt',
      tag: '≈0.5–1.2 g',
      color: '#e76f51',
      fact: '≈0.5–1.2 g of salt in one packet — and you can taste every grain of it.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈260–280 kcal',
      color: '#ff8c42',
      fact: '≈260–280 kcal from a packet you can finish in a minute, mostly from the oil.',
    },
  ],
  pasta: [
    {
      id: 'protein',
      icon: <Zap size={20} color="#1c6b48" />,
      name: 'Protein',
      tag: '≈8 g',
      color: '#06d6a0',
      fact: '≈8 g of protein in one cup — more than most people expect from something this plain.',
    },
    {
      id: 'starch',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Starch, Not Sugar',
      tag: '≈43 g carbs',
      color: '#ff8c42',
      fact: 'Of ≈43 g of carbohydrate, only ≈1 g is sugar. The rest is starch, which burns slowly.',
    },
    {
      id: 'minerals',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Iron & Folate',
      tag: '≈115 µg folate',
      color: '#8bd450',
      fact: '≈115 µg of folate, ≈2 mg of iron and ≈120 mg of potassium, for ≈220 kcal.',
    },
  ],
  bread: [
    {
      id: 'protein',
      icon: <Zap size={20} color="#1c6b48" />,
      name: 'Protein',
      tag: '≈5–6 g',
      color: '#06d6a0',
      fact: '≈5–6 g of protein and ≈1.5–2 g of fibre from two slices.',
    },
    {
      id: 'sodium',
      icon: <Sparkles size={20} color="#e76f51" />,
      name: 'Hidden Salt',
      tag: '≈250–350 mg',
      color: '#e76f51',
      fact: 'Bread never tastes salty, and yet two slices carry ≈250–350 mg of sodium.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈155–165 kcal',
      color: '#ff8c42',
      fact: '≈155–165 kcal, mostly starch, with only ≈3–4 g of sugar.',
    },
  ],
  taco: [
    {
      id: 'sodium',
      icon: <Sparkles size={20} color="#e76f51" />,
      name: 'The Salt',
      tag: '≈500–800 mg',
      color: '#e76f51',
      fact: '≈500–800 mg of sodium in one taco, spread through the shell, the meat and the sauce.',
    },
    {
      id: 'fibre',
      icon: <Leaf size={20} color="#2c7a3a" />,
      name: 'Real Fibre',
      tag: '≈4–6 g',
      color: '#8bd450',
      fact: '≈4–6 g of fibre — more than any other fast food here, thanks to the beans and vegetables.',
    },
    {
      id: 'fat',
      icon: <Droplet size={20} color="#4dd6ff" />,
      name: 'The Fat',
      tag: '≈8–12 g',
      color: '#4dd6ff',
      fact: '≈8–12 g of fat takes it to ≈220–300 kcal, but ≈8–12 g of protein comes with it.',
    },
  ],
  'hot-dog': [
    {
      id: 'sodium',
      icon: <Sparkles size={20} color="#e76f51" />,
      name: 'The Salt',
      tag: '≈700–1,000 mg',
      color: '#e76f51',
      fact: '≈700–1,000 mg of sodium in one hot dog — the saltiest single item in the game.',
    },
    {
      id: 'fat',
      icon: <Droplet size={20} color="#4dd6ff" />,
      name: 'The Fat',
      tag: '≈15–18 g',
      color: '#4dd6ff',
      fact: '≈15–18 g of fat is ground right into the sausage, which is most of its ≈250–300 kcal.',
    },
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Hidden Sugar',
      tag: '≈2–4 g',
      color: '#ff6b9d',
      fact: 'Nothing about a hot dog tastes sweet, yet ≈2–4 g of sugar is in the bun and the sauces.',
    },
  ],
  'cheese-fries': [
    {
      id: 'fat',
      icon: <Droplet size={20} color="#4dd6ff" />,
      name: 'The Fat',
      tag: '≈18–22 g',
      color: '#4dd6ff',
      fact: '≈18–22 g of fat — frying oil in the chips, milk fat in the cheese on top.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈350–450 kcal',
      color: '#ff8c42',
      fact: '≈350–450 kcal from one side order, the largest number on this whole sheet.',
    },
    {
      id: 'sodium',
      icon: <Sparkles size={20} color="#e76f51" />,
      name: 'The Salt',
      tag: '≈600–1,000 mg',
      color: '#e76f51',
      fact: '≈600–1,000 mg of sodium, with only ≈1–3 g of sugar. Here the problem is salt and oil.',
    },
  ],
  waffle: [
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Sugar',
      tag: '≈5–8 g',
      color: '#ff6b9d',
      fact: '≈5–8 g is already in the batter, before anyone pours syrup over the top.',
    },
    {
      id: 'fat',
      icon: <Droplet size={20} color="#4dd6ff" />,
      name: 'The Fat',
      tag: '≈7–9 g',
      color: '#4dd6ff',
      fact: '≈7–9 g of fat from the butter and eggs, taking one waffle to ≈200–250 kcal.',
    },
    {
      id: 'fibre',
      icon: <Leaf size={20} color="#2c7a3a" />,
      name: 'Barely Any Fibre',
      tag: '≈1–2 g',
      color: '#8bd450',
      fact: 'Only ≈1–2 g. Refined flour has had its fibre stripped out, so it stops filling you up quickly.',
    },
  ],
  cake: [
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Sugar',
      tag: '≈25–30 g',
      color: '#ff6b9d',
      fact: '≈25–30 g in one slice — six or seven teaspoons, all in a few mouthfuls.',
    },
    {
      id: 'fat',
      icon: <Droplet size={20} color="#4dd6ff" />,
      name: 'The Fat',
      tag: '≈12–16 g',
      color: '#4dd6ff',
      fact: '≈12–16 g of butter and cream fat, which is what makes the crumb feel soft.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈300–350 kcal',
      color: '#ff8c42',
      fact: '≈300–350 kcal from 80 g, with only ≈1 g of fibre and ≈4–5 g of protein to show for it.',
    },
  ],
  pancakes: [
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Sugar',
      tag: '≈20–25 g',
      color: '#ff6b9d',
      fact: '≈20–25 g, and most of it is the syrup poured on at the table.',
    },
    {
      id: 'carbs',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Carbohydrates',
      tag: '≈55–60 g',
      color: '#ff8c42',
      fact: '≈55–60 g of carbohydrate — the biggest carbohydrate load of any food here, at ≈330–400 kcal.',
    },
    {
      id: 'protein',
      icon: <Zap size={20} color="#1c6b48" />,
      name: 'Protein',
      tag: '≈7–9 g',
      color: '#06d6a0',
      fact: 'There is real protein too — ≈7–9 g from the eggs and milk in the batter.',
    },
  ],
  cupcake: [
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Sugar',
      tag: '≈20–25 g',
      color: '#ff6b9d',
      fact: '≈20–25 g of a 60 g cupcake is sugar. A third of its whole weight.',
    },
    {
      id: 'fat',
      icon: <Droplet size={20} color="#4dd6ff" />,
      name: 'The Fat',
      tag: '≈8–12 g',
      color: '#4dd6ff',
      fact: '≈8–12 g of fat, mostly in the frosting swirl on top.',
    },
    {
      id: 'protein',
      icon: <Zap size={20} color="#9aa5ad" />,
      name: 'Very Little Else',
      tag: '≈2–4 g protein',
      color: '#9aa5ad',
      fact: 'Only ≈2–4 g of protein and ≈1 g of fibre inside ≈220–280 kcal.',
    },
  ],
  candy: [
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Sugar',
      tag: '≈15–18 g',
      color: '#ff6b9d',
      fact: '≈15–18 g of a 20 g serving is sugar. There is very little in candy that is not.',
    },
    {
      id: 'empty',
      icon: <Zap size={20} color="#9aa5ad" />,
      name: 'Nothing Else',
      tag: '0 g protein',
      color: '#9aa5ad',
      fact: 'No protein and no fibre at all, and only ≈1–3 g of water in the whole serving.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈70–80 kcal',
      color: '#ff8c42',
      fact: '≈70–80 kcal that arrive on their own, with nothing for your body to build from.',
    },
  ],
  'bubble-tea': [
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Added Sugar',
      tag: '≈30–50 g',
      color: '#ff6b9d',
      fact: '≈30–50 g of added sugar in one cup — up to twelve teaspoons, and you never chew once.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Liquid Energy',
      tag: '≈200–350+ kcal',
      color: '#ff8c42',
      fact: 'A meal\u2019s worth of energy in a drink — and a drink does not make you feel full.',
    },
    {
      id: 'water',
      icon: <Droplet size={20} color="#4dd6ff" />,
      name: 'Mostly Water',
      tag: '≈400–450 g',
      color: '#4dd6ff',
      fact: 'Nearly all of the 500 mL is water. That is exactly what makes the sugar so easy to miss.',
    },
  ],
  spinach: [
    {
      id: 'iron',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Iron',
      tag: '≈6 mg',
      color: '#e76f51',
      fact: '≈6 mg of iron and a giant load of Vitamin K from one small green leaf — heavy work for spinach.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈40 kcal',
      color: '#ff8c42',
      fact: 'A whole cooked cup is ≈40 kcal and still lands ≈5 g of protein and ≈4 g of fibre.',
    },
    {
      id: 'potassium',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Potassium',
      tag: '≈840 mg',
      color: '#06d6a0',
      fact: '≈840 mg of potassium and ≈195 µg of folate in that same cup — a leafy powerhouse.',
    },
  ],
  cucumber: [
    {
      id: 'water',
      icon: <Droplet size={20} color="#4dd6ff" />,
      name: 'Mostly Water',
      tag: '≈194 g',
      color: '#4dd6ff',
      fact: '≈194 g of every 200 g is water — that is why a cucumber is cold, crunchy and barely sweet.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈30 kcal',
      color: '#ff8c42',
      fact: 'One whole cucumber is only ≈30 kcal — the crunchiest low-energy snack there is.',
    },
    {
      id: 'potassium',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Potassium',
      tag: '≈300 mg',
      color: '#06d6a0',
      fact: 'Even watery cucumbers sneak in ≈300 mg of potassium and a little Vitamin K.',
    },
  ],
  cabbage: [
    {
      id: 'vitamin-c',
      icon: <Citrus size={20} color="#8bd450" />,
      name: 'Vitamin C',
      tag: '≈36 mg',
      color: '#06d6a0',
      fact: '≈36 mg of Vitamin C and ≈68 µg of Vitamin K in one crunchy cup.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈22 kcal',
      color: '#ff8c42',
      fact: 'A whole cup of raw cabbage is ≈22 kcal — about the lightest thing on your plate.',
    },
    {
      id: 'minerals',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Potassium & Folate',
      tag: '≈220 mg',
      color: '#8bd450',
      fact: '≈220 mg of potassium and ≈50 µg of folate, all wrapped in ≈2 g of fibre.',
    },
  ],
  'green-peas': [
    {
      id: 'protein',
      icon: <Zap size={20} color="#1c6b48" />,
      name: 'Protein',
      tag: '≈8.5 g',
      color: '#06d6a0',
      fact: '≈8.5 g of protein and ≈8 g of fibre packed into those tiny round balls.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈135 kcal',
      color: '#ff8c42',
      fact: 'A full cooked cup is ≈135 kcal — growing power from peas, not from sugar.',
    },
    {
      id: 'minerals',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Folate & Iron',
      tag: '≈100 µg folate',
      color: '#8bd450',
      fact: '≈100 µg of folate, ≈2.5 mg of iron and ≈430 mg of potassium in the same cup.',
    },
  ],
  capsicum: [
    {
      id: 'vitamin-c',
      icon: <Citrus size={20} color="#8bd450" />,
      name: 'Vitamin C',
      tag: '≈100 mg',
      color: '#06d6a0',
      fact: '≈100 mg of Vitamin C in one medium capsicum — more than most fruits.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈30 kcal',
      color: '#ff8c42',
      fact: 'One whole capsicum is only ≈30 kcal, even though it tastes sweet and crunchy.',
    },
    {
      id: 'potassium',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Potassium',
      tag: '≈250 mg',
      color: '#8bd450',
      fact: '≈250 mg of potassium rides along — and its ≈4 g of sugar comes with fibre to slow it down.',
    },
  ],
  tomato: [
    {
      id: 'lycopene',
      icon: <Sparkles size={20} color="#e76f51" />,
      name: 'Lycopene',
      tag: 'the red stuff',
      color: '#e76f51',
      fact: 'The red colour is lycopene — a healthy pigment that helps protect your cells.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈22 kcal',
      color: '#ff8c42',
      fact: 'A whole tomato is ≈22 kcal and still hands you ≈290 mg of potassium.',
    },
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Hardly Any Sugar',
      tag: '≈3 g',
      color: '#ff6b9d',
      fact: 'Tomatoes taste sweet, yet one holds only ≈3 g of natural sugar.',
    },
  ],
  onion: [
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Natural Sugar',
      tag: '≈5 g',
      color: '#ff6b9d',
      fact: 'That sweetness when onions brown? It is their ≈5 g of natural sugar.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈44 kcal',
      color: '#ff8c42',
      fact: 'A whole medium onion is ≈44 kcal — mostly water and a little starch.',
    },
    {
      id: 'vitamin-c',
      icon: <Citrus size={20} color="#8bd450" />,
      name: 'Vitamin C',
      tag: '≈8 mg',
      color: '#06d6a0',
      fact: 'Even a plain onion carries ≈8 mg of Vitamin C and ≈160 mg of potassium.',
    },
  ],
  garlic: [
    {
      id: 'sulfur',
      icon: <Sparkles size={20} color="#06d6a0" />,
      name: 'Sulfur Power',
      tag: 'the smell',
      color: '#06d6a0',
      fact: 'That famous garlic smell is sulfur compounds — tiny, strong and great for your body.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈13 kcal',
      color: '#ff8c42',
      fact: 'Three whole cloves are ≈13 kcal — huge flavour for almost no energy.',
    },
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Hardly Any Sugar',
      tag: '≈0.3 g',
      color: '#ff6b9d',
      fact: 'Just ≈0.3 g of natural sugar in three cloves — the punch is flavour, not sugar.',
    },
  ],
  pumpkin: [
    {
      id: 'vitamin-a',
      icon: <Citrus size={20} color="#ff8c42" />,
      name: 'Vitamin A',
      tag: 'very high',
      color: '#ff8c42',
      fact: 'Pumpkin is packed with Vitamin A — and that is exactly what makes it orange.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈50 kcal',
      color: '#ff8c42',
      fact: 'A big cooked cup is ≈50 kcal, with ≈560 mg of potassium for your muscles.',
    },
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Mildly Sweet',
      tag: '≈5 g',
      color: '#ff6b9d',
      fact: 'Pumpkin tastes sweet-ish but holds only ≈5 g of natural sugar — nowhere near a sweet treat.',
    },
  ],
  lauki: [
    {
      id: 'water',
      icon: <Droplet size={20} color="#4dd6ff" />,
      name: 'Mostly Water',
      tag: '≈145 g',
      color: '#4dd6ff',
      fact: '≈145 g of every 150 g is water — lauki hydrates you with almost nothing else.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈20 kcal',
      color: '#ff8c42',
      fact: 'A whole cooked cup is ≈20 kcal — one of the lightest foods there is.',
    },
    {
      id: 'potassium',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Potassium',
      tag: '≈170 mg',
      color: '#06d6a0',
      fact: 'Still hiding inside: ≈170 mg of potassium and a little Vitamin C.',
    },
  ],
  rajma: [
    {
      id: 'protein',
      icon: <Zap size={20} color="#1c6b48" />,
      name: 'Protein',
      tag: '≈15 g',
      color: '#06d6a0',
      fact: '≈15 g of protein in one cup — beans grow muscle like chicken does.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈225 kcal',
      color: '#ff8c42',
      fact: '≈225 kcal, but they stay with you for hours — that is the fibre at work.',
    },
    {
      id: 'fibre',
      icon: <Leaf size={20} color="#2c7a3a" />,
      name: 'Fibre & Iron',
      tag: '≈11 g fibre',
      color: '#8bd450',
      fact: '≈11 g of fibre, ≈5 mg of iron and ≈130 µg of folate in the same cup.',
    },
  ],
  'urad-dal': [
    {
      id: 'protein',
      icon: <Zap size={20} color="#1c6b48" />,
      name: 'Protein',
      tag: '≈12 g',
      color: '#06d6a0',
      fact: '≈12 g of protein and ≈8 g of fibre from one humble cup.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈200–220 kcal',
      color: '#ff8c42',
      fact: '≈200–220 kcal of steady energy — a slow burn, not a sugar rush.',
    },
    {
      id: 'iron',
      icon: <Sparkles size={20} color="#e76f51" />,
      name: 'Iron',
      tag: '≈3–4 mg',
      color: '#e76f51',
      fact: '≈3–4 mg of iron for your blood, plus ≈400 mg of potassium.',
    },
  ],
  'moong-dal': [
    {
      id: 'fibre',
      icon: <Leaf size={20} color="#2c7a3a" />,
      name: 'Fibre',
      tag: '≈15 g',
      color: '#8bd450',
      fact: '≈15 g of fibre in one cup — a record among the dals on this sheet.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈210–220 kcal',
      color: '#ff8c42',
      fact: '≈210–220 kcal that release slowly, with ≈14 g of protein for growing.',
    },
    {
      id: 'magnesium',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Magnesium',
      tag: '≈95 mg',
      color: '#06d6a0',
      fact: '≈95 mg of magnesium for your bones and ≈530 mg of potassium.',
    },
  ],
  oats: [
    {
      id: 'fibre',
      icon: <Leaf size={20} color="#2c7a3a" />,
      name: 'Fibre',
      tag: '≈4 g',
      color: '#8bd450',
      fact: '≈4 g of fibre per cup is why a bowl of oats keeps you full till lunch.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈160 kcal',
      color: '#ff8c42',
      fact: '≈160 kcal that burn slowly — energy which lasts all morning.',
    },
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Hardly Any Sugar',
      tag: '≈1 g',
      color: '#ff6b9d',
      fact: 'Plain oats hold only ≈1 g of sugar — the sweet part comes from what you add.',
    },
  ],
  'brown-rice': [
    {
      id: 'fibre',
      icon: <Leaf size={20} color="#2c7a3a" />,
      name: 'Fibre',
      tag: '≈3.5 g',
      color: '#8bd450',
      fact: 'The outer layer stays on brown rice, so ≈3.5 g of fibre and B vitamins hang around.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈215 kcal',
      color: '#ff8c42',
      fact: '≈215 kcal of slow-burning energy in one full cup.',
    },
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Almost No Sugar',
      tag: '≈0.5 g',
      color: '#ff6b9d',
      fact: '≈0.5 g of natural sugar — its energy comes from starch, not sugar.',
    },
  ],
  bajra: [
    {
      id: 'protein',
      icon: <Zap size={20} color="#1c6b48" />,
      name: 'Protein',
      tag: '≈6 g',
      color: '#06d6a0',
      fact: '≈6 g of protein from this small golden grain that grows in hot places.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈200 kcal',
      color: '#ff8c42',
      fact: '≈200 kcal of energy that keeps releasing through the whole day.',
    },
    {
      id: 'minerals',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Iron & Magnesium',
      tag: 'iron + magnesium',
      color: '#8bd450',
      fact: 'Bajra carries iron, magnesium and phosphorus — even where rain is scarce.',
    },
  ],
  ragi: [
    {
      id: 'calcium',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Calcium',
      tag: 'relatively high',
      color: '#06d6a0',
      fact: 'Ragi is unusually rich in calcium — brilliant for growing bones.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈200 kcal',
      color: '#ff8c42',
      fact: '≈200 kcal that stay with you, thanks to its fibre and iron.',
    },
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Starch, Not Sugar',
      tag: 'no sugar spike',
      color: '#ff6b9d',
      fact: 'Its energy arrives as slow starch and fibre — there is no sugar spike at all.',
    },
  ],
  curd: [
    {
      id: 'calcium',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Calcium',
      tag: '≈180 mg',
      color: '#06d6a0',
      fact: '≈180 mg of calcium in one bowl, plus Vitamin B12.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈90–110 kcal',
      color: '#ff8c42',
      fact: '≈90–110 kcal, with ≈5–6 g of protein and friendly bacteria on board.',
    },
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Milk Sugar',
      tag: '≈5–7 g',
      color: '#ff6b9d',
      fact: 'Plain curd holds ≈5–7 g of milk sugar, called lactose — mild next to any sweet treat.',
    },
  ],
  orange: [
    {
      id: 'vitamin-c',
      icon: <Citrus size={20} color="#8bd450" />,
      name: 'Vitamin C',
      tag: '≈70 mg',
      color: '#06d6a0',
      fact: '≈70 mg of Vitamin C in one juicy orange — a full day in a single fruit.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈60 kcal',
      color: '#ff8c42',
      fact: 'One medium orange is ≈60 kcal, and ≈3 g of fibre comes with the sweetness.',
    },
    {
      id: 'minerals',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Potassium',
      tag: '≈240 mg',
      color: '#8bd450',
      fact: '≈240 mg of potassium and ≈40 µg of folate ride along in the juice.',
    },
  ],
  kiwi: [
    {
      id: 'vitamin-c',
      icon: <Citrus size={20} color="#8bd450" />,
      name: 'Vitamin C',
      tag: '≈56 mg',
      color: '#06d6a0',
      fact: 'One little kiwi packs ≈56 mg of Vitamin C — tiny fruit, huge punch.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈45 kcal',
      color: '#ff8c42',
      fact: '≈45 kcal for a whole kiwi, plus ≈2 g of fibre.',
    },
    {
      id: 'minerals',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Vitamin K',
      tag: '≈31 µg',
      color: '#8bd450',
      fact: 'The fuzzy green fruit also hides ≈31 µg of Vitamin K and ≈230 mg of potassium.',
    },
  ],
  pomegranate: [
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Natural Sugar',
      tag: '≈24 g',
      color: '#ff6b9d',
      fact: 'The ruby seeds are sweet — ≈24 g of natural sugar per cup, but ≈7 g of fibre rides with them.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈145 kcal',
      color: '#ff8c42',
      fact: 'A cup of arils is ≈145 kcal of jewel-like energy.',
    },
    {
      id: 'potassium',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Potassium',
      tag: '≈410 mg',
      color: '#06d6a0',
      fact: '≈410 mg of potassium, plus Vitamin C and folate, in every burst.',
    },
  ],
  watermelon: [
    {
      id: 'water',
      icon: <Droplet size={20} color="#4dd6ff" />,
      name: 'Mostly Water',
      tag: '≈139 g',
      color: '#4dd6ff',
      fact: '≈139 g of a 152 g cup is water — the perfect hot-day snack.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈46 kcal',
      color: '#ff8c42',
      fact: 'A whole cup is only ≈46 kcal, even with ≈9.5 g of sweet sugar.',
    },
    {
      id: 'lycopene',
      icon: <Sparkles size={20} color="#e76f51" />,
      name: 'Lycopene',
      tag: 'the pink pigment',
      color: '#e76f51',
      fact: 'The pink colour is lycopene — the same healthy pigment that makes tomatoes red.',
    },
  ],
  papaya: [
    {
      id: 'vitamin-c',
      icon: <Citrus size={20} color="#8bd450" />,
      name: 'Vitamin C',
      tag: '≈88 mg',
      color: '#06d6a0',
      fact: '≈88 mg of Vitamin C in one cup of soft orange cubes.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈62 kcal',
      color: '#ff8c42',
      fact: '≈62 kcal, and the orange colour means plenty of Vitamin A too.',
    },
    {
      id: 'minerals',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Folate & Potassium',
      tag: '≈53 µg folate',
      color: '#8bd450',
      fact: '≈12 g of natural sugar and ≈2.5 g of fibre — with folate and potassium as well.',
    },
  ],
  guava: [
    {
      id: 'vitamin-c',
      icon: <Citrus size={20} color="#8bd450" />,
      name: 'Vitamin C',
      tag: '≈228 mg',
      color: '#06d6a0',
      fact: '≈228 mg of Vitamin C in one guava — more than several oranges together.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈68 kcal',
      color: '#ff8c42',
      fact: 'One whole guava is ≈68 kcal, with ≈417 mg of potassium thrown in.',
    },
    {
      id: 'fibre',
      icon: <Leaf size={20} color="#2c7a3a" />,
      name: 'Fibre',
      tag: '≈5 g',
      color: '#8bd450',
      fact: '≈5 g of fibre in one small fruit is outstanding — guava is a champion.',
    },
  ],
  'sweet-lime': [
    {
      id: 'vitamin-c',
      icon: <Citrus size={20} color="#8bd450" />,
      name: 'Vitamin C',
      tag: '≈35–45 mg',
      color: '#06d6a0',
      fact: '≈35–45 mg of Vitamin C in one pale-green mosambi.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈50 kcal',
      color: '#ff8c42',
      fact: 'A whole sweet lime is ≈50 kcal, and it mostly drinks like water.',
    },
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Milder Than Juice',
      tag: '≈9 g',
      color: '#ff6b9d',
      fact: 'Whole fruit gives ≈9 g of natural sugar with fibre — the juice version does not.',
    },
  ],
  amla: [
    {
      id: 'vitamin-c',
      icon: <Citrus size={20} color="#8bd450" />,
      name: 'Vitamin C',
      tag: 'one of the richest',
      color: '#06d6a0',
      fact: 'Amla is one of the richest natural Vitamin C sources on Earth — a tiny sour ball.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈44 kcal',
      color: '#ff8c42',
      fact: '100 g is only ≈44 kcal, with ≈4–5 g of fibre inside.',
    },
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Hardly Any Sugar',
      tag: '≈4–5 g',
      color: '#ff6b9d',
      fact: 'For a fruit, ≈4–5 g of natural sugar is remarkably little — the sour tells you.',
    },
  ],
  beetroot: [
    {
      id: 'folate',
      icon: <Sparkles size={20} color="#e76f51" />,
      name: 'Folate',
      tag: '≈135 µg',
      color: '#e76f51',
      fact: '≈135 µg of folate in one cup helps your body build brand-new cells.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈75 kcal',
      color: '#ff8c42',
      fact: 'A cooked cup is ≈75 kcal of deep-red root power.',
    },
    {
      id: 'betalains',
      icon: <Sparkles size={20} color="#06d6a0" />,
      name: 'Betalains',
      tag: 'the red pigment',
      color: '#06d6a0',
      fact: 'The deep red colour is a pigment called betalain — no dye added here.',
    },
  ],
  cauliflower: [
    {
      id: 'vitamin-c',
      icon: <Citrus size={20} color="#8bd450" />,
      name: 'Vitamin C',
      tag: '≈48 mg',
      color: '#06d6a0',
      fact: 'Pale and mild, yet ≈48 mg of Vitamin C hides in one cup.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈25 kcal',
      color: '#ff8c42',
      fact: 'A full cup of florets is just ≈25 kcal — crunchy and nearly free of energy.',
    },
    {
      id: 'minerals',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Folate & Potassium',
      tag: '≈57 µg folate',
      color: '#8bd450',
      fact: '≈57 µg of folate and ≈300 mg of potassium hide under all that white.',
    },
  ],
  'green-beans': [
    {
      id: 'fibre',
      icon: <Leaf size={20} color="#2c7a3a" />,
      name: 'Fibre',
      tag: '≈4 g',
      color: '#8bd450',
      fact: '≈4 g of fibre from crisp pods, with ≈2.5 g of protein too.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈44 kcal',
      color: '#ff8c42',
      fact: 'A cooked cup is ≈44 kcal — the crunch is mostly water and fibre.',
    },
    {
      id: 'vitamin-c',
      icon: <Citrus size={20} color="#8bd450" />,
      name: 'Vitamins C & K',
      tag: '≈12 mg C',
      color: '#06d6a0',
      fact: 'Green beans also slip you ≈12 mg of Vitamin C plus Vitamin K.',
    },
  ],
  okra: [
    {
      id: 'minerals',
      icon: <Sparkles size={20} color="#06d6a0" />,
      name: 'Calcium & Folate',
      tag: '≈175 mg calcium',
      color: '#06d6a0',
      fact: '≈175 mg of calcium and ≈75 µg of folate in one cooked cup — brilliant for bones and blood.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈55 kcal',
      color: '#ff8c42',
      fact: '≈55 kcal, with ≈5 g of fibre to help your tummy.',
    },
    {
      id: 'sugar',
      icon: <Candy size={20} color="#ff6b9d" />,
      name: 'Hardly Any Sugar',
      tag: '≈3 g',
      color: '#ff6b9d',
      fact: 'Bhindi holds only ≈3 g of natural sugar — the rest is soft fibre and water.',
    },
  ],
  radish: [
    {
      id: 'bite',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'That Sharp Bite',
      tag: 'plant bite',
      color: '#8bd450',
      fact: 'Radish\u2019s sharp bite is plant compounds doing the talking — not sugar.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈19 kcal',
      color: '#ff8c42',
      fact: '≈19 kcal for a whole cup — about the lightest vegetable you can crunch.',
    },
    {
      id: 'vitamin-c',
      icon: <Citrus size={20} color="#8bd450" />,
      name: 'Vitamin C',
      tag: '≈18 mg',
      color: '#06d6a0',
      fact: '≈18 mg of Vitamin C and ≈270 mg of potassium sneak in while you crunch.',
    },
  ],
  drumstick: [
    {
      id: 'minerals',
      icon: <Sparkles size={20} color="#06d6a0" />,
      name: 'Mineral Pods',
      tag: 'calcium + iron',
      color: '#06d6a0',
      fact: 'Drumstick is Moringa — its long pods carry calcium, iron and potassium.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈45 kcal',
      color: '#ff8c42',
      fact: '100 g of cooked pods is ≈45 kcal — seriously loaded per bite.',
    },
    {
      id: 'protein',
      icon: <Zap size={20} color="#1c6b48" />,
      name: 'Surprising Protein',
      tag: '≈2–3 g',
      color: '#06d6a0',
      fact: 'For a vegetable, ≈2–3 g of protein in 100 g is a plucky amount.',
    },
  ],
  'masoor-dal': [
    {
      id: 'protein',
      icon: <Zap size={20} color="#1c6b48" />,
      name: 'Protein',
      tag: '≈18 g',
      color: '#06d6a0',
      fact: '≈18 g of protein from the little red lentils — a real protein star.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈225 kcal',
      color: '#ff8c42',
      fact: '≈225 kcal of slow-burning lentil energy in one cup.',
    },
    {
      id: 'iron',
      icon: <Sparkles size={20} color="#e76f51" />,
      name: 'Iron',
      tag: '≈6–7 mg',
      color: '#e76f51',
      fact: '≈6–7 mg of iron plus a big dose of folate — lentils help your blood too.',
    },
  ],
  'toor-dal': [
    {
      id: 'fibre',
      icon: <Leaf size={20} color="#2c7a3a" />,
      name: 'Fibre',
      tag: '≈10–12 g',
      color: '#8bd450',
      fact: '≈10–12 g of fibre alongside ≈11–12 g of protein — filling and friendly.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈210–230 kcal',
      color: '#ff8c42',
      fact: '≈210–230 kcal that fill you up slowly — no crash later.',
    },
    {
      id: 'potassium',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Potassium',
      tag: '≈500 mg',
      color: '#06d6a0',
      fact: '≈500 mg of potassium, with iron, folate and magnesium tucked in.',
    },
  ],
  'chana-dal': [
    {
      id: 'protein',
      icon: <Zap size={20} color="#1c6b48" />,
      name: 'Protein',
      tag: '≈9–10 g',
      color: '#06d6a0',
      fact: '≈9–10 g of protein and ≈9 g of fibre from split chickpeas.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈200–220 kcal',
      color: '#ff8c42',
      fact: '≈200–220 kcal of steady, filling energy per cooked cup.',
    },
    {
      id: 'iron',
      icon: <Sparkles size={20} color="#e76f51" />,
      name: 'Iron',
      tag: '≈2–3 mg',
      color: '#e76f51',
      fact: '≈2–3 mg of iron, plus folate and magnesium for good measure.',
    },
  ],
  walnuts: [
    {
      id: 'fat',
      icon: <Droplet size={20} color="#4dd6ff" />,
      name: 'Good Fat',
      tag: '≈20 g',
      color: '#4dd6ff',
      fact: '≈20 g of a 30 g handful is healthy fat — and ≈2.5 g of it is brain-friendly omega-3.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈195 kcal',
      color: '#ff8c42',
      fact: '≈195 kcal in a small handful — the fat makes it rich, so a handful is enough.',
    },
    {
      id: 'magnesium',
      icon: <Sparkles size={20} color="#8bd450" />,
      name: 'Magnesium',
      tag: '≈45 mg',
      color: '#06d6a0',
      fact: 'The crinkly nut also carries ≈45 mg of magnesium and ≈100 mg of phosphorus.',
    },
  ],
  soybeans: [
    {
      id: 'protein',
      icon: <Zap size={20} color="#1c6b48" />,
      name: 'Protein',
      tag: '≈29 g',
      color: '#06d6a0',
      fact: '≈29 g of protein in one cup — the most of any vegetable on this sheet.',
    },
    {
      id: 'calories',
      icon: <Flame size={20} color="#ff8c42" />,
      name: 'Energy',
      tag: '≈295 kcal',
      color: '#ff8c42',
      fact: '≈295 kcal, mostly from ≈15 g of healthy plant fat and ≈10 g of fibre.',
    },
    {
      id: 'calcium',
      icon: <Sparkles size={20} color="#06d6a0" />,
      name: 'Calcium & Iron',
      tag: '≈175 mg calcium',
      color: '#06d6a0',
      fact: 'About ≈175 mg of calcium, like a glass of milk, plus ≈5 mg of iron.',
    },
  ],
};

export default function FlatCrossSection({ foodId }: { foodId: string }) {
  const facts = FLAT_FACTS[foodId] ?? [];
  const micro = MICRO[foodId];
  const FoodModel = FOOD_MODELS[foodId];
  const noCut = NO_CUT_FOODS.has(foodId);
  const cutRef = useRef(noCut ? 0 : 1);
  cutRef.current = noCut ? 0 : 1;

  if (!micro) return null;

  const panelTitle = noCut
    ? (FoodModel ? 'In 3D' : 'Whole Food')
    : (FoodModel ? 'Your cut, in 3D' : 'Your cut');

  return (
    <CrossSectionShell
      facts={facts}
      micro={micro}
      panelTitle={panelTitle}
      hasDots={false}
      scene={
        FoodModel
          ? () => (
              <FitScale target={foodSizeOf(foodId)}>
                <FoodModel cutProgressRef={cutRef} stage="cut" />
              </FitScale>
            )
          : undefined
      }
      flatView={
        !FoodModel ? <FlatCutStage foodId={foodId} cut={!noCut} size={260} /> : undefined
      }
    />
  );
}
