/**
 * What each food actually looks like once you are past the cut face and into
 * the tissue itself. Everything here is procedural — a jittered hex grid with
 * a palette and a few rules — so no micrograph images ship with the app.
 *
 * Note these are honest illustrations of real structure, not photographs. A
 * genuine SEM image of apple parenchyma is a copyrighted photograph; drawing
 * the same anatomy is not.
 */

/** Which cells a label lights up. */
export type CellKind = 'matrix' | 'pocket' | 'vessel' | 'inclusion';

export interface MicroLabel {
  id: string;
  /** Kid-voice, read out loud in a speech bubble. */
  text: string;
  /** The same structure under its proper name, for the science view. */
  sciText: string;
  kind: CellKind;
  /** Where the bubble sits, in the 400x400 viewBox. */
  at: [number, number];
}

export interface MicroSpec {
  /** The ring around the lens. */
  bezel: string;
  /** Background showing between the cells. */
  field: string;
  wall: string;
  matrix: [string, string];
  pocket: string;
  vessel: string;
  inclusion: string;
  cellRadius: number;
  /** 0 = sharp crystal corners, 0.5 = fully round bubble. */
  corner: number;
  jitter: number;
  pocketChance: number;
  inclusionChance: number;
  hasVessel: boolean;
  /** How many cells get a face. Too many and it stops reading as tissue. */
  faces: number;
  /** Ink for the eyes and mouth. Dark ink on a dark chocolate cell is an
   *  invisible face, so this cannot be a constant. */
  faceInk: string;
  caption: string;
  sciCaption: string;
  labels: MicroLabel[];
}

export const MICRO: Record<string, MicroSpec> = {
  apple: {
    bezel: '#1f7a4d',
    field: '#eef8dd',
    wall: '#8fb757',
    matrix: ['#e8f7c6', '#dcf0b2'],
    pocket: '#5f7046',
    vessel: '#e8735c',
    inclusion: '#fffbe3',
    cellRadius: 25,
    corner: 0.4,
    jitter: 3,
    pocketChance: 0.12,
    inclusionChance: 0.45,
    hasVessel: true,
    faces: 4,
    faceInk: '#33421f',
    caption: 'Apple flesh, about 400× bigger',
    sciCaption: 'Malus domestica — fruit parenchyma',
    labels: [
      { id: 'matrix', text: 'Juicy cells, full of water!', sciText: 'Parenchyma Cell Matrix', kind: 'matrix', at: [140, 46] },
      { id: 'pocket', text: 'Air pockets = the crunch!', sciText: 'Intercellular Air Space', kind: 'pocket', at: [268, 126] },
      { id: 'vessel', text: 'Tubes that fed the apple', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  mango: {
    bezel: '#c77d1a',
    field: '#fff3d0',
    wall: '#dda43c',
    matrix: ['#ffe6a0', '#ffd775'],
    pocket: '#9a7530',
    vessel: '#f0913c',
    inclusion: '#fffaea',
    cellRadius: 24,
    corner: 0.44,
    jitter: 3.5,
    pocketChance: 0.08,
    inclusionChance: 0.5,
    hasVessel: true,
    faces: 4,
    faceInk: '#6b4a11',
    caption: 'Mango flesh, about 400× bigger',
    sciCaption: 'Mangifera indica — mesocarp tissue',
    labels: [
      { id: 'matrix', text: 'Soft cells full of sweet juice', sciText: 'Parenchyma Cell Matrix', kind: 'matrix', at: [140, 46] },
      { id: 'inclusion', text: 'Little stores of food', sciText: 'Amyloplast (Starch)', kind: 'inclusion', at: [268, 126] },
      { id: 'vessel', text: 'Stringy juice tubes', sciText: 'Fibrovascular Strand', kind: 'vessel', at: [200, 312] },
    ],
  },
  donut: {
    bezel: '#c9974f',
    field: '#e3bb86',
    wall: '#c08a48',
    matrix: ['#f0d3a4', '#e8c692'],
    pocket: '#fffaf0',
    vessel: '#ffb27a',
    inclusion: '#ffffff',
    cellRadius: 27,
    corner: 0.5,
    jitter: 4,
    pocketChance: 0.5,
    inclusionChance: 0.3,
    hasVessel: false,
    faces: 3,
    faceInk: '#7a4f1c',
    caption: 'Donut crumb, about 400× bigger',
    sciCaption: 'Fried yeast dough — crumb structure',
    labels: [
      { id: 'pocket', text: 'Air bubbles blown by yeast!', sciText: 'Gas Cell (CO\u2082 Void)', kind: 'pocket', at: [140, 46] },
      { id: 'matrix', text: 'Stretchy dough web', sciText: 'Gluten\u2013Starch Matrix', kind: 'matrix', at: [268, 126] },
      { id: 'inclusion', text: 'Sugar crystals everywhere', sciText: 'Sucrose Crystal', kind: 'inclusion', at: [200, 312] },
    ],
  },
  'chocolate-bar': {
    bezel: '#3f2415',
    field: '#3a2114',
    wall: '#2a1610',
    matrix: ['#54301c', '#633a21'],
    pocket: '#7a4a2a',
    vessel: '#8a5a33',
    inclusion: '#f6efe4',
    cellRadius: 19,
    corner: 0.12,
    jitter: 3.5,
    pocketChance: 0.06,
    inclusionChance: 0.55,
    hasVessel: false,
    faces: 3,
    faceInk: '#f3e4cf',
    caption: 'Chocolate, about 400× bigger',
    sciCaption: 'Chocolate — sugar in a fat matrix',
    labels: [
      { id: 'inclusion', text: 'Sugar crystals, packed tight!', sciText: 'Sucrose Crystal', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Ground-up cocoa bits', sciText: 'Cocoa Solid Particle', kind: 'matrix', at: [268, 126] },
      { id: 'pocket', text: 'Cocoa butter glues it all', sciText: 'Cocoa Butter Phase', kind: 'pocket', at: [200, 312] },
    ],
  },
  pineapple: {
    bezel: '#c9951b',
    field: '#fff6d6',
    wall: '#e0b33c',
    matrix: ['#ffeaa0', '#ffdd7a'],
    pocket: '#a78331',
    vessel: '#ef9b3a',
    inclusion: '#fffdf0',
    cellRadius: 23,
    corner: 0.42,
    jitter: 3.5,
    pocketChance: 0.1,
    inclusionChance: 0.5,
    hasVessel: true,
    faces: 4,
    faceInk: '#6d5010',
    caption: 'Pineapple flesh, about 400× bigger',
    sciCaption: 'Ananas comosus — fruit parenchyma',
    labels: [
      { id: 'matrix', text: 'Juicy cells, dripping with water', sciText: 'Parenchyma Cell Matrix', kind: 'matrix', at: [140, 46] },
      { id: 'inclusion', text: 'Tiny specks of Vitamin C', sciText: 'Cytoplasmic Inclusion', kind: 'inclusion', at: [268, 126] },
      { id: 'vessel', text: 'Stringy bits you chew on', sciText: 'Fibrovascular Strand', kind: 'vessel', at: [200, 312] },
    ],
  },
  corn: {
    bezel: '#c9a01b',
    field: '#fff8dc',
    wall: '#dcb33f',
    matrix: ['#ffe79a', '#ffda6f'],
    pocket: '#9c7b28',
    vessel: '#eda93c',
    inclusion: '#ffffff',
    cellRadius: 22,
    corner: 0.34,
    jitter: 3,
    pocketChance: 0.12,
    inclusionChance: 0.62,
    hasVessel: false,
    faces: 4,
    faceInk: '#6b5310',
    caption: 'Corn kernel, about 400× bigger',
    sciCaption: 'Zea mays — endosperm tissue',
    labels: [
      { id: 'matrix', text: 'Kernel cells stuffed with food', sciText: 'Endosperm Cell Matrix', kind: 'matrix', at: [140, 46] },
      { id: 'inclusion', text: 'Starch grains — slow energy', sciText: 'Starch Granule', kind: 'inclusion', at: [268, 126] },
      { id: 'pocket', text: 'Little gaps make it pop', sciText: 'Intercellular Air Space', kind: 'pocket', at: [200, 312] },
    ],
  },
  'sweet-potato': {
    bezel: '#b35d18',
    field: '#ffeddb',
    wall: '#d98442',
    matrix: ['#ffd0a0', '#ffbe80'],
    pocket: '#94531f',
    vessel: '#e0702a',
    inclusion: '#fff6ea',
    cellRadius: 24,
    corner: 0.4,
    jitter: 3.2,
    pocketChance: 0.1,
    inclusionChance: 0.66,
    hasVessel: true,
    faces: 4,
    faceInk: '#6d3a10',
    caption: 'Sweet potato, about 400× bigger',
    sciCaption: 'Ipomoea batatas — storage root parenchyma',
    labels: [
      { id: 'inclusion', text: 'Packed food stores inside', sciText: 'Amyloplast (Starch)', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Orange cells full of goodness', sciText: 'Storage Parenchyma', kind: 'matrix', at: [268, 126] },
      { id: 'vessel', text: 'Tubes that fed the root', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  burger: {
    bezel: '#8a5a33',
    field: '#e9d3b4',
    wall: '#b4844f',
    matrix: ['#d9ab74', '#c89660'],
    pocket: '#fff6e6',
    vessel: '#a2582f',
    inclusion: '#fff1cf',
    cellRadius: 24,
    corner: 0.46,
    jitter: 4,
    pocketChance: 0.4,
    inclusionChance: 0.42,
    hasVessel: false,
    faces: 3,
    faceInk: '#5e3a17',
    caption: 'Burger, about 400× bigger',
    sciCaption: 'Wheat crumb with cooked muscle fibre',
    labels: [
      { id: 'pocket', text: 'Air holes in the soft bun', sciText: 'Gas Cell (Crumb Void)', kind: 'pocket', at: [140, 46] },
      { id: 'matrix', text: 'Squishy bread and meat', sciText: 'Gluten–Starch Matrix', kind: 'matrix', at: [268, 126] },
      { id: 'inclusion', text: 'Blobs of fat and salt', sciText: 'Lipid Droplet', kind: 'inclusion', at: [200, 312] },
    ],
  },
  egg: {
    bezel: '#c79a2f',
    field: '#fffaea',
    wall: '#e6cf95',
    matrix: ['#fff3cf', '#ffe7ab'],
    pocket: '#b39a5c',
    vessel: '#f0b838',
    inclusion: '#ffd45e',
    cellRadius: 21,
    corner: 0.48,
    jitter: 3.8,
    pocketChance: 0.08,
    inclusionChance: 0.58,
    hasVessel: false,
    faces: 4,
    faceInk: '#6a521a',
    caption: 'Cooked egg, about 400× bigger',
    sciCaption: 'Coagulated egg protein network',
    labels: [
      { id: 'matrix', text: 'A net of protein, set solid', sciText: 'Coagulated Protein Network', kind: 'matrix', at: [140, 46] },
      { id: 'inclusion', text: 'Yolk droplets — the vitamins', sciText: 'Yolk Lipoprotein Granule', kind: 'inclusion', at: [268, 126] },
      { id: 'pocket', text: 'Water trapped in the net', sciText: 'Entrapped Water Pocket', kind: 'pocket', at: [200, 312] },
    ],
  },
  carrot: {
    bezel: '#c25f13',
    field: '#ffeada',
    wall: '#e08a45',
    matrix: ['#ffca9a', '#ffb676'],
    pocket: '#9b5620',
    vessel: '#e7671f',
    inclusion: '#ff8c2b',
    cellRadius: 23,
    corner: 0.38,
    jitter: 3,
    pocketChance: 0.1,
    inclusionChance: 0.6,
    hasVessel: true,
    faces: 4,
    faceInk: '#6e3a11',
    caption: 'Carrot, about 400× bigger',
    sciCaption: 'Daucus carota — root parenchyma',
    labels: [
      { id: 'inclusion', text: 'Orange specks for your eyes', sciText: 'Carotene Crystal', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Crunchy cells full of water', sciText: 'Root Parenchyma Cell', kind: 'matrix', at: [268, 126] },
      { id: 'vessel', text: 'The core that drank water up', sciText: 'Xylem Vessel', kind: 'vessel', at: [200, 312] },
    ],
  },
  milk: {
    bezel: '#7f96a8',
    field: '#f2f8fc',
    wall: '#cfe0ec',
    matrix: ['#ffffff', '#f2f7fb'],
    pocket: '#dbe8f1',
    vessel: '#bcd4e4',
    inclusion: '#fff3c4',
    cellRadius: 20,
    corner: 0.5,
    jitter: 4.2,
    pocketChance: 0.14,
    inclusionChance: 0.7,
    hasVessel: false,
    faces: 3,
    faceInk: '#5b6f80',
    caption: 'Milk, about 400× bigger',
    sciCaption: 'Milk — fat globules in water',
    labels: [
      { id: 'inclusion', text: 'Little drops of milk fat', sciText: 'Milk Fat Globule', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Watery milk all around', sciText: 'Aqueous Serum Phase', kind: 'matrix', at: [268, 126] },
      { id: 'pocket', text: 'Air whisked in as bubbles', sciText: 'Entrained Air Bubble', kind: 'pocket', at: [200, 312] },
    ],
  },
  broccoli: {
    bezel: '#1f7a4d',
    field: '#e9f7dd',
    wall: '#6ea542',
    matrix: ['#cdeeb0', '#b9e498'],
    pocket: '#4f6b39',
    vessel: '#8fc44f',
    inclusion: '#f6ffe6',
    cellRadius: 22,
    corner: 0.42,
    jitter: 3.4,
    pocketChance: 0.14,
    inclusionChance: 0.52,
    hasVessel: true,
    faces: 4,
    faceInk: '#2c4419',
    caption: 'Broccoli floret, about 400× bigger',
    sciCaption: 'Brassica oleracea — floret parenchyma',
    labels: [
      { id: 'matrix', text: 'Green cells busy making food', sciText: 'Chlorenchyma Cell', kind: 'matrix', at: [140, 46] },
      { id: 'inclusion', text: 'Stores of Vitamin C', sciText: 'Cytoplasmic Inclusion', kind: 'inclusion', at: [268, 126] },
      { id: 'vessel', text: 'Water pipes up the stalk', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  peanuts: {
    bezel: '#9a6b2c',
    field: '#f6e7cb',
    wall: '#c69a58',
    matrix: ['#f0d6a6', '#e6c88f'],
    pocket: '#8d6a34',
    vessel: '#c08a44',
    inclusion: '#fffaf0',
    cellRadius: 20,
    corner: 0.44,
    jitter: 3.2,
    pocketChance: 0.07,
    inclusionChance: 0.72,
    hasVessel: false,
    faces: 4,
    faceInk: '#5f421a',
    caption: 'Peanut, about 400× bigger',
    sciCaption: 'Arachis hypogaea — cotyledon cells',
    labels: [
      { id: 'inclusion', text: 'Droplets of peanut oil', sciText: 'Oil Body (Oleosome)', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Seed cells packed with protein', sciText: 'Cotyledon Storage Cell', kind: 'matrix', at: [268, 126] },
      { id: 'pocket', text: 'Small gaps between cells', sciText: 'Intercellular Air Space', kind: 'pocket', at: [200, 312] },
    ],
  },
  'soft-drink': {
    bezel: '#8a4a2a',
    field: '#e7c9a6',
    wall: '#c98d55',
    matrix: ['#e3bb8f', '#d8ad7e'],
    pocket: '#fffdf8',
    vessel: '#b87a44',
    inclusion: '#ffffff',
    cellRadius: 21,
    corner: 0.5,
    jitter: 4.4,
    pocketChance: 0.46,
    inclusionChance: 0.48,
    hasVessel: false,
    faces: 3,
    faceInk: '#6b3f1c',
    caption: 'Soft drink, about 400× bigger',
    sciCaption: 'Sugar solution with dissolved CO₂',
    labels: [
      { id: 'pocket', text: 'Fizzy bubbles of gas!', sciText: 'Carbon Dioxide Bubble', kind: 'pocket', at: [140, 46] },
      { id: 'inclusion', text: 'Sugar, dissolved everywhere', sciText: 'Dissolved Sucrose', kind: 'inclusion', at: [268, 126] },
      { id: 'matrix', text: 'Sugar water — and that is it', sciText: 'Aqueous Sugar Phase', kind: 'matrix', at: [200, 312] },
    ],
  },
  'potato-chips': {
    bezel: '#c08a1d',
    field: '#e8c98c',
    wall: '#c7963f',
    matrix: ['#f2cf86', '#e8c274'],
    pocket: '#fff3d2',
    vessel: '#d9a648',
    inclusion: '#ffffff',
    cellRadius: 22,
    corner: 0.2,
    jitter: 4,
    pocketChance: 0.42,
    inclusionChance: 0.5,
    hasVessel: false,
    faces: 3,
    faceInk: '#6d4c10',
    caption: 'Potato chip, about 400× bigger',
    sciCaption: 'Fried potato — starch matrix and oil',
    labels: [
      { id: 'pocket', text: 'Holes where water fried away', sciText: 'Oil-Filled Void', kind: 'pocket', at: [140, 46] },
      { id: 'matrix', text: 'Crispy potato starch', sciText: 'Gelatinised Starch Matrix', kind: 'matrix', at: [268, 126] },
      { id: 'inclusion', text: 'Salt crystals on top', sciText: 'Sodium Chloride Crystal', kind: 'inclusion', at: [200, 312] },
    ],
  },
  'cream-biscuits': {
    bezel: '#9c6530',
    field: '#e6cfae',
    wall: '#bd8c50',
    matrix: ['#e4bd8a', '#d8ac77'],
    pocket: '#fff8ea',
    vessel: '#c08a4c',
    inclusion: '#ffffff',
    cellRadius: 20,
    corner: 0.22,
    jitter: 3.6,
    pocketChance: 0.3,
    inclusionChance: 0.62,
    hasVessel: false,
    faces: 3,
    faceInk: '#5d3d16',
    caption: 'Cream biscuit, about 400× bigger',
    sciCaption: 'Biscuit crumb — sugar in a fat matrix',
    labels: [
      { id: 'inclusion', text: 'Sugar crystals, packed tight!', sciText: 'Sucrose Crystal', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Crumbly dough and cream fat', sciText: 'Flour–Fat Matrix', kind: 'matrix', at: [268, 126] },
      { id: 'pocket', text: 'Air pockets from baking', sciText: 'Gas Cell (Crumb Void)', kind: 'pocket', at: [200, 312] },
    ],
  },
  pasta: {
    bezel: '#c9a227',
    field: '#f7edd2',
    wall: '#d8bd74',
    matrix: ['#f9f0d6', '#f2e5c1'],
    pocket: '#fffdf6',
    vessel: '#e0c67e',
    inclusion: '#ffffff',
    cellRadius: 24,
    corner: 0.45,
    jitter: 3.4,
    pocketChance: 0.2,
    inclusionChance: 0.5,
    hasVessel: false,
    faces: 3,
    faceInk: '#8a6d20',
    caption: 'Cooked pasta, about 400× bigger',
    sciCaption: 'Durum wheat — gelatinised starch in gluten',
    labels: [
      { id: 'inclusion', text: 'Starch grains, swollen fat', sciText: 'Gelatinised Starch Granule', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Stretchy gluten holds it together', sciText: 'Gluten Protein Network', kind: 'matrix', at: [268, 126] },
      { id: 'pocket', text: 'Water it drank while boiling', sciText: 'Absorbed Water Void', kind: 'pocket', at: [200, 312] },
    ],
  },
  bread: {
    bezel: '#b5813c',
    field: '#f6e5c4',
    wall: '#dcbb84',
    matrix: ['#faeed5', '#f2e0bd'],
    pocket: '#fffdf7',
    vessel: '#e3c488',
    inclusion: '#fff8e6',
    cellRadius: 28,
    corner: 0.5,
    jitter: 4.2,
    pocketChance: 0.5,
    inclusionChance: 0.32,
    hasVessel: false,
    faces: 3,
    faceInk: '#7d5b1f',
    caption: 'Bread crumb, about 400× bigger',
    sciCaption: 'Leavened wheat dough — crumb structure',
    labels: [
      { id: 'pocket', text: 'Bubbles the yeast blew!', sciText: 'Gas Cell (CO\u2082 Void)', kind: 'pocket', at: [140, 46] },
      { id: 'matrix', text: 'A gluten web around each bubble', sciText: 'Gluten–Starch Matrix', kind: 'matrix', at: [268, 126] },
      { id: 'inclusion', text: 'Starch grains in the walls', sciText: 'Starch Granule', kind: 'inclusion', at: [200, 312] },
    ],
  },
  taco: {
    bezel: '#c07a2a',
    field: '#f0d6a8',
    wall: '#cf9a4f',
    matrix: ['#f5ddb0', '#ecd09c'],
    pocket: '#fff6e4',
    vessel: '#c1492f',
    inclusion: '#ffffff',
    cellRadius: 23,
    corner: 0.35,
    jitter: 4,
    pocketChance: 0.3,
    inclusionChance: 0.42,
    hasVessel: true,
    faces: 3,
    faceInk: '#7a4a15',
    caption: 'Taco filling, about 400× bigger',
    sciCaption: 'Maize masa, meat fibre and vegetable tissue',
    labels: [
      { id: 'matrix', text: 'Ground corn from the shell', sciText: 'Maize Starch Matrix', kind: 'matrix', at: [140, 46] },
      { id: 'vessel', text: 'Threads of meat fibre', sciText: 'Skeletal Muscle Fibre', kind: 'vessel', at: [268, 126] },
      { id: 'inclusion', text: 'Salt, everywhere you look', sciText: 'Sodium Chloride Crystal', kind: 'inclusion', at: [200, 312] },
    ],
  },
  'hot-dog': {
    bezel: '#a83c42',
    field: '#f3c9c3',
    wall: '#d98d85',
    matrix: ['#f6d3cc', '#eec2ba'],
    pocket: '#fffaf6',
    vessel: '#b14a3e',
    inclusion: '#ffffff',
    cellRadius: 20,
    corner: 0.5,
    jitter: 4.4,
    pocketChance: 0.44,
    inclusionChance: 0.5,
    hasVessel: false,
    faces: 3,
    faceInk: '#7d3029',
    caption: 'Hot dog sausage, about 400× bigger',
    sciCaption: 'Meat emulsion — fat droplets in protein gel',
    labels: [
      { id: 'pocket', text: 'Droplets of fat, everywhere', sciText: 'Emulsified Fat Globule', kind: 'pocket', at: [140, 46] },
      { id: 'matrix', text: 'Meat ground down into paste', sciText: 'Myofibrillar Protein Gel', kind: 'matrix', at: [268, 126] },
      { id: 'inclusion', text: 'Salt used to cure it', sciText: 'Curing Salt Crystal', kind: 'inclusion', at: [200, 312] },
    ],
  },
  'cheese-fries': {
    bezel: '#c98a10',
    field: '#f5d78f',
    wall: '#d5a43c',
    matrix: ['#f8dc9b', '#f0cd83'],
    pocket: '#fff6df',
    vessel: '#e88c2a',
    inclusion: '#ffffff',
    cellRadius: 24,
    corner: 0.28,
    jitter: 4.2,
    pocketChance: 0.5,
    inclusionChance: 0.46,
    hasVessel: false,
    faces: 3,
    faceInk: '#6f4b0c',
    caption: 'Cheese fries, about 400× bigger',
    sciCaption: 'Fried potato starch under a milk-fat layer',
    labels: [
      { id: 'pocket', text: 'Holes the frying oil filled', sciText: 'Oil-Filled Void', kind: 'pocket', at: [140, 46] },
      { id: 'matrix', text: 'Potato starch, cooked soft', sciText: 'Gelatinised Starch Matrix', kind: 'matrix', at: [268, 126] },
      { id: 'inclusion', text: 'Salt from the chips and the cheese', sciText: 'Sodium Chloride Crystal', kind: 'inclusion', at: [200, 312] },
    ],
  },
  waffle: {
    bezel: '#b8801f',
    field: '#f4dda6',
    wall: '#d7ae5c',
    matrix: ['#f8e6bb', '#f0daa6'],
    pocket: '#fffdf4',
    vessel: '#e0bd72',
    inclusion: '#fff6dd',
    cellRadius: 26,
    corner: 0.5,
    jitter: 4,
    pocketChance: 0.46,
    inclusionChance: 0.34,
    hasVessel: false,
    faces: 3,
    faceInk: '#7b5615',
    caption: 'Waffle crumb, about 400× bigger',
    sciCaption: 'Baked batter — starch, egg protein and fat',
    labels: [
      { id: 'pocket', text: 'Air whisked into the batter', sciText: 'Entrapped Air Cell', kind: 'pocket', at: [140, 46] },
      { id: 'matrix', text: 'Flour and egg, baked firm', sciText: 'Starch–Egg Protein Matrix', kind: 'matrix', at: [268, 126] },
      { id: 'inclusion', text: 'Fat from the butter', sciText: 'Dispersed Fat Droplet', kind: 'inclusion', at: [200, 312] },
    ],
  },
  cake: {
    bezel: '#c96b86',
    field: '#f8e2cd',
    wall: '#e0b58f',
    matrix: ['#fbeedd', '#f4e0c8'],
    pocket: '#fffdfa',
    vessel: '#ef9bb4',
    inclusion: '#ffffff',
    cellRadius: 29,
    corner: 0.5,
    jitter: 4.6,
    pocketChance: 0.54,
    inclusionChance: 0.44,
    hasVessel: false,
    faces: 3,
    faceInk: '#8a5a3a',
    caption: 'Cake sponge, about 400× bigger',
    sciCaption: 'Aerated sponge — starch, fat and sucrose',
    labels: [
      { id: 'pocket', text: 'Air, and lots of it', sciText: 'Entrapped Air Cell', kind: 'pocket', at: [140, 46] },
      { id: 'inclusion', text: 'Sugar crystals in every crumb', sciText: 'Sucrose Crystal', kind: 'inclusion', at: [268, 126] },
      { id: 'matrix', text: 'Soft crumb, heavy with fat', sciText: 'Starch–Fat Matrix', kind: 'matrix', at: [200, 312] },
    ],
  },
  pancakes: {
    bezel: '#a9661f',
    field: '#f2d9a8',
    wall: '#d4a758',
    matrix: ['#f7e3ba', '#efd6a4'],
    pocket: '#fff8e8',
    vessel: '#c07c2a',
    inclusion: '#ffeab5',
    cellRadius: 26,
    corner: 0.5,
    jitter: 4.2,
    pocketChance: 0.4,
    inclusionChance: 0.5,
    hasVessel: false,
    faces: 3,
    faceInk: '#78521a',
    caption: 'Pancake and syrup, about 400× bigger',
    sciCaption: 'Batter crumb saturated with sugar syrup',
    labels: [
      { id: 'inclusion', text: 'Syrup soaked right in', sciText: 'Absorbed Sugar Syrup', kind: 'inclusion', at: [140, 46] },
      { id: 'pocket', text: 'Bubbles from the raising agent', sciText: 'Gas Cell (CO\u2082 Void)', kind: 'pocket', at: [268, 126] },
      { id: 'matrix', text: 'Flour, milk and egg, cooked', sciText: 'Starch–Protein Matrix', kind: 'matrix', at: [200, 312] },
    ],
  },
  cupcake: {
    bezel: '#d1748f',
    field: '#fbe6ee',
    wall: '#eeb3c8',
    matrix: ['#fdeff4', '#f8e2ea'],
    pocket: '#fffdfe',
    vessel: '#f096b4',
    inclusion: '#ffffff',
    cellRadius: 27,
    corner: 0.5,
    jitter: 4.4,
    pocketChance: 0.48,
    inclusionChance: 0.5,
    hasVessel: false,
    faces: 3,
    faceInk: '#9c4f6a',
    caption: 'Cupcake and frosting, about 400× bigger',
    sciCaption: 'Sponge crumb beneath a sugar–fat icing',
    labels: [
      { id: 'inclusion', text: 'Icing sugar, packed tight', sciText: 'Sucrose Crystal', kind: 'inclusion', at: [140, 46] },
      { id: 'pocket', text: 'Air beaten into the mix', sciText: 'Entrapped Air Cell', kind: 'pocket', at: [268, 126] },
      { id: 'matrix', text: 'Butter keeping the crumb soft', sciText: 'Fat-Coated Starch Matrix', kind: 'matrix', at: [200, 312] },
    ],
  },
  'ice-cream': {
    bezel: '#7fa9d6',
    field: '#eef6fd',
    wall: '#c6dcf0',
    matrix: ['#f7fbff', '#e9f3fc'],
    pocket: '#ffffff',
    vessel: '#b9d4ee',
    inclusion: '#fde3ec',
    cellRadius: 22,
    corner: 0.45,
    jitter: 4,
    pocketChance: 0.5,
    inclusionChance: 0.46,
    hasVessel: false,
    faces: 3,
    faceInk: '#4a6b8c',
    caption: 'Ice cream, about 400× bigger',
    sciCaption: 'Frozen foam — ice crystals, air cells, milk fat',
    labels: [
      { id: 'pocket', text: 'Air whipped in — nearly half of it!', sciText: 'Air Cell (Overrun)', kind: 'pocket', at: [140, 46] },
      { id: 'matrix', text: 'Tiny crystals of ice', sciText: 'Ice Crystal Phase', kind: 'matrix', at: [268, 126] },
      { id: 'inclusion', text: 'Milk fat and sugar in between', sciText: 'Milk Fat Globule', kind: 'inclusion', at: [200, 312] },
    ],
  },
  lollipop: {
    bezel: '#c2344f',
    field: '#fde8ee',
    wall: '#f3a8bd',
    matrix: ['#fef1f5', '#fce0e8'],
    pocket: '#ffffff',
    vessel: '#ef476f',
    inclusion: '#ffffff',
    cellRadius: 30,
    corner: 0.12,
    jitter: 2.2,
    pocketChance: 0.12,
    inclusionChance: 0.55,
    hasVessel: false,
    faces: 3,
    faceInk: '#9c2740',
    caption: 'Lollipop, about 400× bigger',
    sciCaption: 'Amorphous sugar glass — boiled sucrose',
    labels: [
      { id: 'matrix', text: 'Sugar cooled into glass', sciText: 'Amorphous Sugar Glass', kind: 'matrix', at: [140, 46] },
      { id: 'inclusion', text: 'Colour and flavour — nothing else', sciText: 'Dispersed Colourant', kind: 'inclusion', at: [268, 126] },
      { id: 'pocket', text: 'A rare trapped bubble', sciText: 'Entrapped Air Bubble', kind: 'pocket', at: [200, 312] },
    ],
  },
  candy: {
    bezel: '#2f6fb5',
    field: '#e3f0fd',
    wall: '#9fc6ec',
    matrix: ['#eaf4fe', '#d9eafb'],
    pocket: '#ffffff',
    vessel: '#4a90d9',
    inclusion: '#ffffff',
    cellRadius: 26,
    corner: 0.05,
    jitter: 3,
    pocketChance: 0.14,
    inclusionChance: 0.58,
    hasVessel: false,
    faces: 3,
    faceInk: '#245a94',
    caption: 'Candy, about 400× bigger',
    sciCaption: 'Crystalline sucrose with colourants',
    labels: [
      { id: 'inclusion', text: 'Sugar crystals, edge to edge', sciText: 'Sucrose Crystal', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Boiled sugar, set hard', sciText: 'Solidified Sugar Mass', kind: 'matrix', at: [268, 126] },
      { id: 'pocket', text: 'Almost no water in here', sciText: 'Residual Moisture Void', kind: 'pocket', at: [200, 312] },
    ],
  },
  'bubble-tea': {
    bezel: '#8a5a33',
    field: '#f0dcc4',
    wall: '#cfa878',
    matrix: ['#f5e5d2', '#ecd8be'],
    pocket: '#fffaf4',
    vessel: '#4a2d1c',
    inclusion: '#ffffff',
    cellRadius: 23,
    corner: 0.5,
    jitter: 4,
    pocketChance: 0.3,
    inclusionChance: 0.52,
    hasVessel: true,
    faces: 3,
    faceInk: '#6b4526',
    caption: 'Bubble tea, about 400× bigger',
    sciCaption: 'Sweetened tea with tapioca starch pearls',
    labels: [
      { id: 'inclusion', text: 'Sugar dissolved in the tea', sciText: 'Dissolved Sucrose', kind: 'inclusion', at: [140, 46] },
      { id: 'vessel', text: 'Chewy tapioca pearls', sciText: 'Gelatinised Tapioca Starch', kind: 'vessel', at: [268, 126] },
      { id: 'matrix', text: 'Mostly water — which hides the sugar', sciText: 'Aqueous Sugar Phase', kind: 'matrix', at: [200, 312] },
    ],
  },
  spinach: {
    bezel: '#1b6e3c',
    field: '#eaf6d8',
    wall: '#5f9c3a',
    matrix: ['#c6e598', '#b3dc83'],
    pocket: '#3f5c2a',
    vessel: '#7cb83f',
    inclusion: '#f6ffde',
    cellRadius: 20,
    corner: 0.4,
    jitter: 3.2,
    pocketChance: 0.25,
    inclusionChance: 0.4,
    hasVessel: true,
    faces: 4,
    faceInk: '#2c4518',
    caption: 'Spinach leaf, about 600× bigger',
    sciCaption: 'Spinacia oleracea — leaf mesophyll',
    labels: [
      { id: 'matrix', text: 'Chloroplast-packed cells', sciText: 'Chlorenchyma (Mesophyll Cell)', kind: 'matrix', at: [140, 46] },
      { id: 'pocket', text: 'Air gaps for the leaf to breathe', sciText: 'Spongy Intercellular Space', kind: 'pocket', at: [268, 126] },
      { id: 'vessel', text: 'Veins that carried water', sciText: 'Leaf Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  cucumber: {
    bezel: '#4d8a3a',
    field: '#eef7e4',
    wall: '#9cbe70',
    matrix: ['#e2f2cf', '#d5ecbd'],
    pocket: '#5b7a44',
    vessel: '#8fc064',
    inclusion: '#ffffff',
    cellRadius: 26,
    corner: 0.5,
    jitter: 4,
    pocketChance: 0.2,
    inclusionChance: 0.35,
    hasVessel: true,
    faces: 3,
    faceInk: '#3c5426',
    caption: 'Cucumber, about 400× bigger',
    sciCaption: 'Cucumis sativus — fruit parenchyma',
    labels: [
      { id: 'matrix', text: 'Crisp cells, mostly water', sciText: 'Fruit Parenchyma Cell', kind: 'matrix', at: [140, 46] },
      { id: 'pocket', text: 'Air gaps = the crunch!', sciText: 'Intercellular Air Space', kind: 'pocket', at: [268, 126] },
      { id: 'vessel', text: 'Tubes that fed the fruit', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  cabbage: {
    bezel: '#4f8a5a',
    field: '#f0f6ec',
    wall: '#a9c493',
    matrix: ['#e6f0dc', '#dcead1'],
    pocket: '#5d7a50',
    vessel: '#86b574',
    inclusion: '#f7fbf0',
    cellRadius: 24,
    corner: 0.45,
    jitter: 3.4,
    pocketChance: 0.28,
    inclusionChance: 0.3,
    hasVessel: true,
    faces: 3,
    faceInk: '#415a38',
    caption: 'Cabbage leaf, about 500× bigger',
    sciCaption: 'Brassica oleracea — leafy storage tissue',
    labels: [
      { id: 'matrix', text: 'Leaf cells full of water', sciText: 'Leaf Parenchyma Cell', kind: 'matrix', at: [140, 46] },
      { id: 'pocket', text: 'Air spaces between the leaves', sciText: 'Intercellular Air Space', kind: 'pocket', at: [268, 126] },
      { id: 'vessel', text: 'Veins feeding each layer', sciText: 'Leaf Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  'green-peas': {
    bezel: '#4f8a3c',
    field: '#f2f6d8',
    wall: '#99b25c',
    matrix: ['#dcebb0', '#d0e49e'],
    pocket: '#5c6b38',
    vessel: '#7fa043',
    inclusion: '#fffbe8',
    cellRadius: 23,
    corner: 0.3,
    jitter: 3,
    pocketChance: 0.12,
    inclusionChance: 0.62,
    hasVessel: false,
    faces: 4,
    faceInk: '#44531f',
    caption: 'Green pea, about 400× bigger',
    sciCaption: 'Pisum sativum — cotyledon tissue',
    labels: [
      { id: 'inclusion', text: 'Stuffed little food stores', sciText: 'Starch Granule', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Seed cells plumped with energy', sciText: 'Cotyledon Storage Cell', kind: 'matrix', at: [268, 126] },
      { id: 'pocket', text: 'Gaps as the seed swelled', sciText: 'Intercellular Air Space', kind: 'pocket', at: [200, 312] },
    ],
  },
  capsicum: {
    bezel: '#c2402a',
    field: '#fde8df',
    wall: '#e2937c',
    matrix: ['#f7c9b4', '#f2b8a0'],
    pocket: '#8f3a28',
    vessel: '#d85f3a',
    inclusion: '#fff4ea',
    cellRadius: 24,
    corner: 0.42,
    jitter: 3.2,
    pocketChance: 0.16,
    inclusionChance: 0.45,
    hasVessel: true,
    faces: 4,
    faceInk: '#7a2c1a',
    caption: 'Capsicum, about 400× bigger',
    sciCaption: 'Capsicum annuum — fruit pericarp parenchyma',
    labels: [
      { id: 'matrix', text: 'Crunchy cells, full and juicy', sciText: 'Fruit Pericarp Cell', kind: 'matrix', at: [140, 46] },
      { id: 'pocket', text: 'Air gaps for the crisp bite', sciText: 'Intercellular Air Space', kind: 'pocket', at: [268, 126] },
      { id: 'vessel', text: 'Tubes running down the wall', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  tomato: {
    bezel: '#c1351f',
    field: '#fee9e0',
    wall: '#e28a6e',
    matrix: ['#f7b8a4', '#f3aa92'],
    pocket: '#8f3424',
    vessel: '#e05c38',
    inclusion: '#fff4da',
    cellRadius: 25,
    corner: 0.42,
    jitter: 3.5,
    pocketChance: 0.12,
    inclusionChance: 0.5,
    hasVessel: true,
    faces: 5,
    faceInk: '#7a2410',
    caption: 'Tomato, about 400× bigger',
    sciCaption: 'Solanum lycopersicum — fruit parenchyma',
    labels: [
      { id: 'matrix', text: 'Juicy cells, full of lycopene', sciText: 'Fruit Parenchyma Cell', kind: 'matrix', at: [140, 46] },
      { id: 'inclusion', text: 'Soft edible seeds', sciText: 'Fruit Seed', kind: 'inclusion', at: [268, 126] },
      { id: 'vessel', text: 'Tubes that fed the fruit', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  onion: {
    bezel: '#7d5a8a',
    field: '#f6eef2',
    wall: '#c9a8c9',
    matrix: ['#f1e2ec', '#e9d5e4'],
    pocket: '#8a6b87',
    vessel: '#b78cbc',
    inclusion: '#fffdfe',
    cellRadius: 27,
    corner: 0.48,
    jitter: 4,
    pocketChance: 0.2,
    inclusionChance: 0.38,
    hasVessel: false,
    faces: 4,
    faceInk: '#6b4768',
    caption: 'Onion, about 400× bigger',
    sciCaption: 'Allium cepa — bulb scale parenchyma',
    labels: [
      { id: 'matrix', text: 'Thin watery cells', sciText: 'Bulb Scale Parenchyma', kind: 'matrix', at: [140, 46] },
      { id: 'pocket', text: 'Crisp air gaps', sciText: 'Intercellular Air Space', kind: 'pocket', at: [268, 126] },
      { id: 'inclusion', text: 'Tiny stores of plant sugar', sciText: 'Sucrose Inclusion', kind: 'inclusion', at: [200, 312] },
    ],
  },
  garlic: {
    bezel: '#b08a5a',
    field: '#f6ecdd',
    wall: '#cfa574',
    matrix: ['#f3e7d2', '#ecdcbe'],
    pocket: '#8a6b45',
    vessel: '#c0925c',
    inclusion: '#fffdf5',
    cellRadius: 24,
    corner: 0.4,
    jitter: 3.2,
    pocketChance: 0.08,
    inclusionChance: 0.6,
    hasVessel: false,
    faces: 4,
    faceInk: '#6b4a22',
    caption: 'Garlic clove, about 400× bigger',
    sciCaption: 'Allium sativum — bulb scale storage tissue',
    labels: [
      { id: 'matrix', text: 'Clove cells packed with storage', sciText: 'Bulb Scale Storage Cell', kind: 'matrix', at: [140, 46] },
      { id: 'inclusion', text: 'Strong-smelling oil droplets', sciText: 'Allicin Oil Droplet', kind: 'inclusion', at: [268, 126] },
      { id: 'pocket', text: 'Small gaps between cells', sciText: 'Intercellular Air Space', kind: 'pocket', at: [200, 312] },
    ],
  },
  pumpkin: {
    bezel: '#c96b1a',
    field: '#fff0d6',
    wall: '#e3a052',
    matrix: ['#ffdc9e', '#ffcf80'],
    pocket: '#9a6528',
    vessel: '#e5852f',
    inclusion: '#fff9e8',
    cellRadius: 25,
    corner: 0.42,
    jitter: 3.4,
    pocketChance: 0.14,
    inclusionChance: 0.55,
    hasVessel: true,
    faces: 4,
    faceInk: '#7a4c10',
    caption: 'Pumpkin flesh, about 400× bigger',
    sciCaption: 'Cucurbita pepo — fruit mesocarp',
    labels: [
      { id: 'matrix', text: 'Soft cells full of Vitamin A', sciText: 'Mesocarp Parenchyma Cell', kind: 'matrix', at: [140, 46] },
      { id: 'inclusion', text: 'Orange specks of beta-carotene', sciText: 'Carotenoid Inclusion', kind: 'inclusion', at: [268, 126] },
      { id: 'vessel', text: 'Tubes that fed the squash', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  lauki: {
    bezel: '#7a9a4f',
    field: '#f0f5e2',
    wall: '#acbe88',
    matrix: ['#e3ecd0', '#d8e4c0'],
    pocket: '#6b8050',
    vessel: '#93b268',
    inclusion: '#ffffff',
    cellRadius: 26,
    corner: 0.5,
    jitter: 4,
    pocketChance: 0.4,
    inclusionChance: 0.3,
    hasVessel: true,
    faces: 3,
    faceInk: '#5a6b3a',
    caption: 'Lauki flesh, about 400× bigger',
    sciCaption: 'Lagenaria siceraria — fruit parenchyma',
    labels: [
      { id: 'matrix', text: 'Spongy watery cells', sciText: 'Fruit Parenchyma Cell', kind: 'matrix', at: [140, 46] },
      { id: 'pocket', text: 'Big air pockets make it light', sciText: 'Intercellular Air Space', kind: 'pocket', at: [268, 126] },
      { id: 'vessel', text: 'Tubes running the whole length', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  rajma: {
    bezel: '#8a3a2a',
    field: '#f7e8dd',
    wall: '#c98d72',
    matrix: ['#f0d9c6', '#e9cdb5'],
    pocket: '#8c664f',
    vessel: '#a26a4a',
    inclusion: '#fffdf2',
    cellRadius: 22,
    corner: 0.32,
    jitter: 3,
    pocketChance: 0.1,
    inclusionChance: 0.62,
    hasVessel: false,
    faces: 4,
    faceInk: '#6b4226',
    caption: 'Rajma, about 400× bigger',
    sciCaption: 'Phaseolus vulgaris — cotyledon tissue',
    labels: [
      { id: 'inclusion', text: 'Starch packed into every cell', sciText: 'Starch Granule', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Protein-rich seed cells', sciText: 'Cotyledon Storage Cell', kind: 'matrix', at: [268, 126] },
      { id: 'pocket', text: 'Small gaps between cells', sciText: 'Intercellular Air Space', kind: 'pocket', at: [200, 312] },
    ],
  },
  'urad-dal': {
    bezel: '#5a4036',
    field: '#efe6dc',
    wall: '#b0987e',
    matrix: ['#e5d4bd', '#dcc9ae'],
    pocket: '#6e583f',
    vessel: '#8a7357',
    inclusion: '#fff8e8',
    cellRadius: 22,
    corner: 0.3,
    jitter: 3,
    pocketChance: 0.1,
    inclusionChance: 0.6,
    hasVessel: false,
    faces: 4,
    faceInk: '#4a3722',
    caption: 'Urad dal, about 400× bigger',
    sciCaption: 'Vigna mungo — cotyledon tissue',
    labels: [
      { id: 'inclusion', text: 'Starch stores, packed tight', sciText: 'Starch Granule', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Seed cells full of protein', sciText: 'Cotyledon Storage Cell', kind: 'matrix', at: [268, 126] },
      { id: 'pocket', text: 'Small gaps between cells', sciText: 'Intercellular Air Space', kind: 'pocket', at: [200, 312] },
    ],
  },
  'moong-dal': {
    bezel: '#c99c1a',
    field: '#fdf0c8',
    wall: '#dfc060',
    matrix: ['#f8e39a', '#f3da85'],
    pocket: '#9a7c28',
    vessel: '#d3a83c',
    inclusion: '#fffdf0',
    cellRadius: 22,
    corner: 0.32,
    jitter: 3.2,
    pocketChance: 0.1,
    inclusionChance: 0.6,
    hasVessel: false,
    faces: 4,
    faceInk: '#7a6010',
    caption: 'Moong dal, about 400× bigger',
    sciCaption: 'Vigna radiata — cotyledon tissue',
    labels: [
      { id: 'inclusion', text: 'Starch stores, packed tight', sciText: 'Starch Granule', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Seed cells full of protein', sciText: 'Cotyledon Storage Cell', kind: 'matrix', at: [268, 126] },
      { id: 'pocket', text: 'Small gaps between cells', sciText: 'Intercellular Air Space', kind: 'pocket', at: [200, 312] },
    ],
  },
  oats: {
    bezel: '#a87c3f',
    field: '#f6ecda',
    wall: '#cfae78',
    matrix: ['#f0e0ba', '#e9d7ac'],
    pocket: '#86683c',
    vessel: '#b58f54',
    inclusion: '#fffdf4',
    cellRadius: 21,
    corner: 0.3,
    jitter: 3,
    pocketChance: 0.14,
    inclusionChance: 0.62,
    hasVessel: false,
    faces: 4,
    faceInk: '#6b4c20',
    caption: 'Oat kernel, about 500× bigger',
    sciCaption: 'Avena sativa — endosperm tissue',
    labels: [
      { id: 'inclusion', text: 'Starch grains, ready to go', sciText: 'Starch Granule', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Grain cells with sticky fibre', sciText: 'Endosperm Cell (Beta-Glucan)', kind: 'matrix', at: [268, 126] },
      { id: 'pocket', text: 'Tiny voids in the grain', sciText: 'Intercellular Air Space', kind: 'pocket', at: [200, 312] },
    ],
  },
  'brown-rice': {
    bezel: '#8a5a26',
    field: '#f4e8d0',
    wall: '#c09a5c',
    matrix: ['#ecdcb4', '#e4d1a2'],
    pocket: '#7a5c2c',
    vessel: '#a8883f',
    inclusion: '#fffdf0',
    cellRadius: 24,
    corner: 0.26,
    jitter: 3,
    pocketChance: 0.12,
    inclusionChance: 0.65,
    hasVessel: false,
    faces: 4,
    faceInk: '#6b4a14',
    caption: 'Brown rice kernel, about 500× bigger',
    sciCaption: 'Oryza sativa — endosperm with bran',
    labels: [
      { id: 'inclusion', text: 'Starch-filled food stores', sciText: 'Endosperm Starch Granule', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Rice cells full of energy', sciText: 'Endosperm Cell', kind: 'matrix', at: [268, 126] },
      { id: 'pocket', text: 'Small gaps left after cooking', sciText: 'Cooked Starch Void', kind: 'pocket', at: [200, 312] },
    ],
  },
  bajra: {
    bezel: '#a89a6a',
    field: '#f3ecd4',
    wall: '#c8bd8f',
    matrix: ['#ece2b8', '#e3d7a4'],
    pocket: '#7d7448',
    vessel: '#a89a60',
    inclusion: '#fffff4',
    cellRadius: 20,
    corner: 0.28,
    jitter: 2.8,
    pocketChance: 0.12,
    inclusionChance: 0.6,
    hasVessel: false,
    faces: 4,
    faceInk: '#6a5f28',
    caption: 'Bajra grain, about 500× bigger',
    sciCaption: 'Pennisetum glaucum — endosperm tissue',
    labels: [
      { id: 'inclusion', text: 'Starch grains, tiny and tight', sciText: 'Starch Granule', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Millet cells full of food', sciText: 'Endosperm Cell', kind: 'matrix', at: [268, 126] },
      { id: 'pocket', text: 'Small air gaps', sciText: 'Intercellular Air Space', kind: 'pocket', at: [200, 312] },
    ],
  },
  ragi: {
    bezel: '#8a4a3a',
    field: '#f5e6dd',
    wall: '#c29078',
    matrix: ['#eccdb8', '#e4c2aa'],
    pocket: '#7a4638',
    vessel: '#a2624a',
    inclusion: '#fff8ee',
    cellRadius: 22,
    corner: 0.3,
    jitter: 3,
    pocketChance: 0.12,
    inclusionChance: 0.58,
    hasVessel: false,
    faces: 4,
    faceInk: '#6b3a26',
    caption: 'Ragi grain, about 500× bigger',
    sciCaption: 'Eleusine coracana — endosperm tissue',
    labels: [
      { id: 'inclusion', text: 'Starch grains for slow energy', sciText: 'Starch Granule', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Dark grain cells, rich in iron', sciText: 'Endosperm Cell', kind: 'matrix', at: [268, 126] },
      { id: 'pocket', text: 'Small gaps between cells', sciText: 'Intercellular Air Space', kind: 'pocket', at: [200, 312] },
    ],
  },
  curd: {
    bezel: '#7f96a8',
    field: '#f4f7f4',
    wall: '#cfdcd4',
    matrix: ['#ffffff', '#f2f7f2'],
    pocket: '#e5ece8',
    vessel: '#c6d6cc',
    inclusion: '#ffe9c4',
    cellRadius: 19,
    corner: 0.5,
    jitter: 4.2,
    pocketChance: 0.28,
    inclusionChance: 0.5,
    hasVessel: false,
    faces: 3,
    faceInk: '#5b6f66',
    caption: 'Curd, about 4000× bigger',
    sciCaption: 'Yogurt — coalesced milk protein network',
    labels: [
      { id: 'matrix', text: 'A protein net, set soft', sciText: 'Casein Protein Network', kind: 'matrix', at: [140, 46] },
      { id: 'pocket', text: 'Watery whey trapped in between', sciText: 'Whey Serum Pocket', kind: 'pocket', at: [268, 126] },
      { id: 'inclusion', text: 'Friendly bacteria clusters', sciText: 'Lactic Acid Bacteria Colony', kind: 'inclusion', at: [200, 312] },
    ],
  },
  orange: {
    bezel: '#d2691a',
    field: '#fff0d4',
    wall: '#e5a354',
    matrix: ['#ffdf96', '#ffd27c'],
    pocket: '#9c6a28',
    vessel: '#e8892f',
    inclusion: '#fff9e6',
    cellRadius: 23,
    corner: 0.44,
    jitter: 3.5,
    pocketChance: 0.14,
    inclusionChance: 0.5,
    hasVessel: true,
    faces: 4,
    faceInk: '#7a4c12',
    caption: 'Orange flesh, about 400× bigger',
    sciCaption: 'Citrus sinensis — juice sac parenchyma',
    labels: [
      { id: 'matrix', text: 'Juice sacs full of sweetness', sciText: 'Juice Sac Parenchyma', kind: 'matrix', at: [140, 46] },
      { id: 'pocket', text: 'Air pockets between segments', sciText: 'Intercellular Air Space', kind: 'pocket', at: [268, 126] },
      { id: 'vessel', text: 'Tubes feeding the fruit', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  kiwi: {
    bezel: '#7a8f3f',
    field: '#eef4de',
    wall: '#a9bd6c',
    matrix: ['#d3e7a0', '#c8e08f'],
    pocket: '#6f7c4a',
    vessel: '#8fae52',
    inclusion: '#5a4632',
    cellRadius: 24,
    corner: 0.44,
    jitter: 3.4,
    pocketChance: 0.16,
    inclusionChance: 0.55,
    hasVessel: true,
    faces: 4,
    faceInk: '#45531f',
    caption: 'Kiwi flesh, about 400× bigger',
    sciCaption: 'Actinidia deliciosa — fruit parenchyma',
    labels: [
      { id: 'matrix', text: 'Green juicy cells', sciText: 'Fruit Parenchyma Cell', kind: 'matrix', at: [140, 46] },
      { id: 'inclusion', text: 'Tiny black seeds inside', sciText: 'Fruit Seed', kind: 'inclusion', at: [268, 126] },
      { id: 'vessel', text: 'Pale tubes that fed the fruit', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  pomegranate: {
    bezel: '#a8303a',
    field: '#fbe6ea',
    wall: '#d98a92',
    matrix: ['#f5b7c1', '#f1aab5'],
    pocket: '#8f3a44',
    vessel: '#c26068',
    inclusion: '#ffe9c4',
    cellRadius: 21,
    corner: 0.5,
    jitter: 4,
    pocketChance: 0.18,
    inclusionChance: 0.6,
    hasVessel: false,
    faces: 4,
    faceInk: '#7a232c',
    caption: 'Pomegranate aril, about 400× bigger',
    sciCaption: 'Punica granatum — aril flesh',
    labels: [
      { id: 'matrix', text: 'Juicy red cells around the seed', sciText: 'Aril Parenchyma Cell', kind: 'matrix', at: [140, 46] },
      { id: 'inclusion', text: 'The hard little seed in the middle', sciText: 'Hard Seed Coat', kind: 'inclusion', at: [268, 126] },
      { id: 'pocket', text: 'Crisp gaps between cells', sciText: 'Intercellular Air Space', kind: 'pocket', at: [200, 312] },
    ],
  },
  watermelon: {
    bezel: '#c26a58',
    field: '#fdece8',
    wall: '#e2a290',
    matrix: ['#f6cfc4', '#f2c4b8'],
    pocket: '#8f4a3c',
    vessel: '#d87c68',
    inclusion: '#f2e8b8',
    cellRadius: 28,
    corner: 0.5,
    jitter: 4.4,
    pocketChance: 0.2,
    inclusionChance: 0.5,
    hasVessel: true,
    faces: 4,
    faceInk: '#7a3a28',
    caption: 'Watermelon, about 300× bigger',
    sciCaption: 'Citrullus lanatus — fruit parenchyma',
    labels: [
      { id: 'matrix', text: 'Huge watery cells', sciText: 'Fruit Parenchyma Cell', kind: 'matrix', at: [140, 46] },
      { id: 'inclusion', text: 'Shiny black seeds in rows', sciText: 'Fruit Seed', kind: 'inclusion', at: [268, 126] },
      { id: 'vessel', text: 'Stringy tubes that drank water', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  papaya: {
    bezel: '#d98a2a',
    field: '#fff0d0',
    wall: '#e8b25c',
    matrix: ['#ffdf9e', '#fbd181'],
    pocket: '#9a6a26',
    vessel: '#e8852a',
    inclusion: '#fff8e6',
    cellRadius: 25,
    corner: 0.44,
    jitter: 3.6,
    pocketChance: 0.16,
    inclusionChance: 0.55,
    hasVessel: true,
    faces: 4,
    faceInk: '#7a5210',
    caption: 'Papaya flesh, about 400× bigger',
    sciCaption: 'Carica papaya — fruit mesocarp',
    labels: [
      { id: 'matrix', text: 'Soft cells, super juicy', sciText: 'Mesocarp Parenchyma Cell', kind: 'matrix', at: [140, 46] },
      { id: 'inclusion', text: 'Shiny black seeds inside', sciText: 'Fruit Seed', kind: 'inclusion', at: [268, 126] },
      { id: 'vessel', text: 'Tubes that fed the fruit', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  guava: {
    bezel: '#7a9a4a',
    field: '#f0f4df',
    wall: '#a9c070',
    matrix: ['#dcedb2', '#d0e6a0'],
    pocket: '#6d7c44',
    vessel: '#8fa854',
    inclusion: '#f7f3d8',
    cellRadius: 24,
    corner: 0.44,
    jitter: 3.2,
    pocketChance: 0.14,
    inclusionChance: 0.58,
    hasVessel: true,
    faces: 4,
    faceInk: '#46551f',
    caption: 'Guava flesh, about 400× bigger',
    sciCaption: 'Psidium guajava — fruit pericarp',
    labels: [
      { id: 'matrix', text: 'Firm juicy cells', sciText: 'Fruit Pericarp Cell', kind: 'matrix', at: [140, 46] },
      { id: 'inclusion', text: 'Gritty little stone cells', sciText: 'Sclereid (Stone Cell)', kind: 'inclusion', at: [268, 126] },
      { id: 'vessel', text: 'Tubes feeding the fruit', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  'sweet-lime': {
    bezel: '#9a9a3f',
    field: '#f1f4d8',
    wall: '#c2c46a',
    matrix: ['#e6ecae', '#dde5a0'],
    pocket: '#7d8238',
    vessel: '#aab047',
    inclusion: '#fffdf2',
    cellRadius: 24,
    corner: 0.46,
    jitter: 3.6,
    pocketChance: 0.16,
    inclusionChance: 0.5,
    hasVessel: true,
    faces: 4,
    faceInk: '#5f6418',
    caption: 'Sweet lime, about 400× bigger',
    sciCaption: 'Citrus limetta — juice sac parenchyma',
    labels: [
      { id: 'matrix', text: 'Watery juice cells', sciText: 'Juice Sac Parenchyma', kind: 'matrix', at: [140, 46] },
      { id: 'pocket', text: 'Air pockets between segments', sciText: 'Intercellular Air Space', kind: 'pocket', at: [268, 126] },
      { id: 'vessel', text: 'Tubes feeding the fruit', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  amla: {
    bezel: '#8a9a3f',
    field: '#eef2d6',
    wall: '#b2bd68',
    matrix: ['#dde7a6', '#d3df96'],
    pocket: '#7a8238',
    vessel: '#96a847',
    inclusion: '#fffdf0',
    cellRadius: 24,
    corner: 0.44,
    jitter: 3.4,
    pocketChance: 0.16,
    inclusionChance: 0.55,
    hasVessel: true,
    faces: 4,
    faceInk: '#5a6618',
    caption: 'Amla flesh, about 400× bigger',
    sciCaption: 'Phyllanthus emblica — fruit parenchyma',
    labels: [
      { id: 'matrix', text: 'Tangy green cells', sciText: 'Fruit Parenchyma Cell', kind: 'matrix', at: [140, 46] },
      { id: 'inclusion', text: 'Intense Vitamin C stores', sciText: 'Cytoplasmic Inclusion', kind: 'inclusion', at: [268, 126] },
      { id: 'vessel', text: 'Tubes feeding the fruit', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  beetroot: {
    bezel: '#8a2448',
    field: '#fae3eb',
    wall: '#ce7898',
    matrix: ['#f0a6c0', '#eb9ab6'],
    pocket: '#7a2a4a',
    vessel: '#c05378',
    inclusion: '#f7d4c0',
    cellRadius: 24,
    corner: 0.4,
    jitter: 3.2,
    pocketChance: 0.14,
    inclusionChance: 0.55,
    hasVessel: true,
    faces: 4,
    faceInk: '#6b1c38',
    caption: 'Beetroot, about 400× bigger',
    sciCaption: 'Beta vulgaris — storage root parenchyma',
    labels: [
      { id: 'matrix', text: 'Betalain-dyed cells', sciText: 'Betalain-Rich Parenchyma', kind: 'matrix', at: [140, 46] },
      { id: 'pocket', text: 'Air spaces for the crunch', sciText: 'Intercellular Air Space', kind: 'pocket', at: [268, 126] },
      { id: 'vessel', text: 'Root tubes that drank water', sciText: 'Xylem Vessel', kind: 'vessel', at: [200, 312] },
    ],
  },
  cauliflower: {
    bezel: '#a9a487',
    field: '#f4f3ea',
    wall: '#cecab0',
    matrix: ['#f0eee0', '#e9e7d4'],
    pocket: '#8a8768',
    vessel: '#b4b092',
    inclusion: '#ffffff',
    cellRadius: 23,
    corner: 0.44,
    jitter: 3.4,
    pocketChance: 0.18,
    inclusionChance: 0.46,
    hasVessel: true,
    faces: 4,
    faceInk: '#6b684a',
    caption: 'Cauliflower floret, about 400× bigger',
    sciCaption: 'Brassica oleracea — curd parenchyma',
    labels: [
      { id: 'matrix', text: 'Tight white floral cells', sciText: 'Curd Parenchyma Cell', kind: 'matrix', at: [140, 46] },
      { id: 'pocket', text: 'Small air gaps in the curd', sciText: 'Intercellular Air Space', kind: 'pocket', at: [268, 126] },
      { id: 'vessel', text: 'Tubes that fed the floret', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  'green-beans': {
    bezel: '#4f8a3a',
    field: '#eff6e2',
    wall: '#88ab56',
    matrix: ['#d6eaa8', '#c9e298'],
    pocket: '#566f36',
    vessel: '#6f9c40',
    inclusion: '#fffbe0',
    cellRadius: 24,
    corner: 0.42,
    jitter: 3.2,
    pocketChance: 0.14,
    inclusionChance: 0.5,
    hasVessel: true,
    faces: 4,
    faceInk: '#3f5c1e',
    caption: 'Green bean, about 400× bigger',
    sciCaption: 'Phaseolus vulgaris — pod mesocarp',
    labels: [
      { id: 'matrix', text: 'Crisp pod cells', sciText: 'Pod Mesocarp Cell', kind: 'matrix', at: [140, 46] },
      { id: 'inclusion', text: 'Little beans forming inside', sciText: 'Developing Seed', kind: 'inclusion', at: [268, 126] },
      { id: 'vessel', text: 'Stringy fibres along the pod', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  okra: {
    bezel: '#6f8a3f',
    field: '#eef5e2',
    wall: '#9cb86a',
    matrix: ['#d5e8ac', '#c8e19a'],
    pocket: '#54683a',
    vessel: '#7fa34c',
    inclusion: '#eef5d8',
    cellRadius: 22,
    corner: 0.44,
    jitter: 3.4,
    pocketChance: 0.3,
    inclusionChance: 0.42,
    hasVessel: true,
    faces: 4,
    faceInk: '#41551c',
    caption: 'Okra, about 400× bigger',
    sciCaption: 'Abelmoschus esculentus — pod mesocarp with mucilage',
    labels: [
      { id: 'matrix', text: 'Slime-coated juicy cells', sciText: 'Pod Mesocarp Cell', kind: 'matrix', at: [140, 46] },
      { id: 'pocket', text: 'Big mucilage pockets — the slime!', sciText: 'Mucilage Pocket', kind: 'pocket', at: [268, 126] },
      { id: 'vessel', text: 'Tubes running up the pod', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  radish: {
    bezel: '#c95c3f',
    field: '#fcebe2',
    wall: '#e2a08c',
    matrix: ['#f6d5c8', '#f0c9bb'],
    pocket: '#8f4a38',
    vessel: '#d07258',
    inclusion: '#ffffff',
    cellRadius: 25,
    corner: 0.44,
    jitter: 3.6,
    pocketChance: 0.2,
    inclusionChance: 0.4,
    hasVessel: true,
    faces: 4,
    faceInk: '#6b3520',
    caption: 'Radish, about 400× bigger',
    sciCaption: 'Raphanus sativus — storage root parenchyma',
    labels: [
      { id: 'matrix', text: 'Crisp cool cells', sciText: 'Storage Root Parenchyma', kind: 'matrix', at: [140, 46] },
      { id: 'pocket', text: 'Crunchy air pockets', sciText: 'Intercellular Air Space', kind: 'pocket', at: [268, 126] },
      { id: 'vessel', text: 'Tubes that drank water up', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  drumstick: {
    bezel: '#6f8a3a',
    field: '#eef5e0',
    wall: '#94ac58',
    matrix: ['#cfde9c', '#c2d48a'],
    pocket: '#4f6734',
    vessel: '#74983f',
    inclusion: '#f6fadc',
    cellRadius: 23,
    corner: 0.42,
    jitter: 3.2,
    pocketChance: 0.14,
    inclusionChance: 0.52,
    hasVessel: true,
    faces: 4,
    faceInk: '#3d521c',
    caption: 'Drumstick pod, about 400× bigger',
    sciCaption: 'Moringa oleifera — pod mesocarp',
    labels: [
      { id: 'matrix', text: 'Firm green pod cells', sciText: 'Pod Mesocarp Cell', kind: 'matrix', at: [140, 46] },
      { id: 'inclusion', text: 'Tiny seeds forming inside', sciText: 'Developing Seed', kind: 'inclusion', at: [268, 126] },
      { id: 'vessel', text: 'Tubes running along the pod', sciText: 'Vascular Bundle', kind: 'vessel', at: [200, 312] },
    ],
  },
  'masoor-dal': {
    bezel: '#b04a30',
    field: '#faebe2',
    wall: '#dd9c83',
    matrix: ['#f4cfb8', '#efc6ac'],
    pocket: '#8a4a34',
    vessel: '#b0674a',
    inclusion: '#fff8ec',
    cellRadius: 22,
    corner: 0.32,
    jitter: 3,
    pocketChance: 0.1,
    inclusionChance: 0.6,
    hasVessel: false,
    faces: 4,
    faceInk: '#8a3a22',
    caption: 'Masoor dal, about 400× bigger',
    sciCaption: 'Lens culinaris — cotyledon tissue',
    labels: [
      { id: 'inclusion', text: 'Starch packed into every cell', sciText: 'Starch Granule', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Seed cells heavy with protein', sciText: 'Cotyledon Storage Cell', kind: 'matrix', at: [268, 126] },
      { id: 'pocket', text: 'Small gaps between cells', sciText: 'Intercellular Air Space', kind: 'pocket', at: [200, 312] },
    ],
  },
  'toor-dal': {
    bezel: '#c9941a',
    field: '#fdf1c8',
    wall: '#e0bd54',
    matrix: ['#f9e495', '#f4dc7f'],
    pocket: '#9c7c26',
    vessel: '#d3a63a',
    inclusion: '#fffdf0',
    cellRadius: 22,
    corner: 0.32,
    jitter: 3,
    pocketChance: 0.1,
    inclusionChance: 0.6,
    hasVessel: false,
    faces: 4,
    faceInk: '#7a5c10',
    caption: 'Toor dal, about 400× bigger',
    sciCaption: 'Cajanus cajan — cotyledon tissue',
    labels: [
      { id: 'inclusion', text: 'Starch stores, packed tight', sciText: 'Starch Granule', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Seed cells full of protein', sciText: 'Cotyledon Storage Cell', kind: 'matrix', at: [268, 126] },
      { id: 'pocket', text: 'Small gaps between cells', sciText: 'Intercellular Air Space', kind: 'pocket', at: [200, 312] },
    ],
  },
  'chana-dal': {
    bezel: '#c9951a',
    field: '#fdf2cc',
    wall: '#dfbc58',
    matrix: ['#f8e69c', '#f3de88'],
    pocket: '#9a7c28',
    vessel: '#d1a53c',
    inclusion: '#fffdf0',
    cellRadius: 22,
    corner: 0.32,
    jitter: 3,
    pocketChance: 0.1,
    inclusionChance: 0.62,
    hasVessel: false,
    faces: 4,
    faceInk: '#7a5c12',
    caption: 'Chana dal, about 400× bigger',
    sciCaption: 'Cicer arietinum — cotyledon tissue',
    labels: [
      { id: 'inclusion', text: 'Starch grains for slow energy', sciText: 'Starch Granule', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Bell-shaped cells full of protein', sciText: 'Cotyledon Storage Cell', kind: 'matrix', at: [268, 126] },
      { id: 'pocket', text: 'Tiny gaps between cells', sciText: 'Intercellular Air Space', kind: 'pocket', at: [200, 312] },
    ],
  },
  walnuts: {
    bezel: '#8a5a2c',
    field: '#f3e6d0',
    wall: '#caa068',
    matrix: ['#ecd3a0', '#e6c992'],
    pocket: '#7a5c34',
    vessel: '#b0885a',
    inclusion: '#fffbe8',
    cellRadius: 20,
    corner: 0.5,
    jitter: 3.5,
    pocketChance: 0.12,
    inclusionChance: 0.65,
    hasVessel: false,
    faces: 3,
    faceInk: '#5f3f1a',
    caption: 'Walnut kernel, about 400× bigger',
    sciCaption: 'Juglans regia — cotyledon storage cells',
    labels: [
      { id: 'inclusion', text: 'Oil droplets in every cell', sciText: 'Oil Body (Oleosome)', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Kernel cells full of healthy fat', sciText: 'Cotyledon Storage Cell', kind: 'matrix', at: [268, 126] },
      { id: 'pocket', text: 'Tiny gaps between cells', sciText: 'Intercellular Air Space', kind: 'pocket', at: [200, 312] },
    ],
  },
  soybeans: {
    bezel: '#b08a3a',
    field: '#f8efd8',
    wall: '#d3b46c',
    matrix: ['#f0e0a8', '#e9d896'],
    pocket: '#8a6c38',
    vessel: '#b99752',
    inclusion: '#fffdf0',
    cellRadius: 21,
    corner: 0.35,
    jitter: 3.2,
    pocketChance: 0.1,
    inclusionChance: 0.62,
    hasVessel: false,
    faces: 4,
    faceInk: '#6b4c14',
    caption: 'Soybean, about 400× bigger',
    sciCaption: 'Glycine max — cotyledon storage cells',
    labels: [
      { id: 'inclusion', text: 'Protein bodies and oil drops', sciText: 'Protein Body & Oil Body', kind: 'inclusion', at: [140, 46] },
      { id: 'matrix', text: 'Cotyledon cells packed with protein', sciText: 'Cotyledon Storage Cell', kind: 'matrix', at: [268, 126] },
      { id: 'pocket', text: 'Small gaps between cells', sciText: 'Intercellular Air Space', kind: 'pocket', at: [200, 312] },
    ],
  },
};
